# About the Author {-}

Dr. Thierry Worch is a Data enthusiast who engineers Simple, Meaningful, Automated, Reproducible, Trustworthy solutions to Sensory and Consumer challenges at FrieslandCampina. 
Back in 2009, he started as a project manager at OP&P Product Research (Utrecht, The Netherlands) before completing his PhD in 2012 on “the Ideal Profile Analysis: from the validation to the statistical analysis of ideal profile data” both in collaboration with Pieter Punter (OP&P), Sébastien Lê and Jérôme Pagès (Agrocampus-Ouest). End of 2012, he joined Qi Statistics as a consultant where he ran clients’ projects, participated to research projects, and gave diverse trainings. During that time, he also continued a long collaboration with Logic8 (EyeQuestion Software) where he produced all the R-routines included in the EyeOpenR software. End of 2019, he joined the Global Sensory Department of Friesland-Campina, Wageningen, The Netherlands, where he provides his expertise in Sensory and Consumer Methods, Sensometric, and Data Science. 
Besides publishing various papers related to Sensometric, and participating in many books, he is also the co-author with Sébastien Lê of the book entitled “Analyzing sensory data with R” (CRC Press).

Dr. Julien Delarue is an Associate Professor in Sensory and Consumer Science at UC Davis. He received his Ph.D. in Food Science at AgroParisTech, and his research focuses on methods to measure sensory perception and preferences and on their effective use in food design.

Dr. Vanessa de Rios Souza is a Sr. Computational Sensory Science Consultant at Aigora, a company whose mission is to empower sensory and consumer science teams to implement artificial intelligence. Her role involves leading clients' projects related to Process Automation, Knowledge Management, New Technologies and Computational Analytics. Vanessa holds a Ph.D. degree in Food Science and has over 10 years of experience in R&D, consumer and sensory research across multiple food product categories and functions, with strong background in food science and food processing. She has extensive experience in industrial, academic, and research settings.

Dr. John Ennis is the co-founder of Aigora, and a world-renowned authority on the use of artificial intelligence within sensory and consumer science. He is a Ph.D. mathematician who conducted his postdoctoral studies in computational neuroscience and who has more than a dozen years of experience as a sensory and consumer science consultant. 
