# Conclusion and Next Steps {#next-steps}

Congratulations, you've reached the end of this book! 

We hope we have motivated you to continue your amazing journey into the emerging field of computational sensory science. To give you a little hand, we are listing here some other resources we would recommend and a summary of the main useful packages for sensory and consumer data analysis/visualization, including the ones we used throughout this book.

## Other Recommended Resources
* *R for Data Science* by Garrett Grolemund and Hadley Wickham (https://r4ds.had.co.nz/)
* *Analyzing Sensory Data with R* by Sebastien Le and Thierry Worch
* *Rapid Sensory Profiling Techniques (2nd Edition)* by Julien Delarue and J. Ben Lawlor
* *Practical Guide to Cluster Analysis in R* by Alboukadel Kassambara
* *Practical Guide to Principal Component Methods in R* by Alboukadel Kassambara
* *Multiple Factor Analysis by Example Using R* by Jerome Pages
* *Using the flextable R package* by David Gohel (https://ardata-fr.github.io/flextable-book/index.html)
* *Tidy Modelling with R* by Max Kuhn and Julia Silge (https://www.tmwr.org/)
* *Hands-On Machine Learning with R* by Brad Boehmke and Brandon Greenwell (https://bradleyboehmke.github.io/HOML/)
* *Introduction to Statistical and Machine Learning Methods for Data Science* by Carlos Andre Reis Pinheiro and Mike Patetta
* *Supervised Machine Learning for Text Analysis in R* by Emil Hvitfeldt and Julia Sigle
* *R Graphics Cookbook: Practical Recipes for Visualizing Data* by Winston Chang
* *Text Mining with R: A Tidy Approach* by David Robinson and Julia Silge
* *Textual Data Science with R* by Mónica Bécue-Bertaut
* *Design and Analysis of Experiments with R* by John Lawson
* *Mastering Shiny* by Hadley Wickham (https://mastering-shiny.org/)

Some interesting book related to story telling, graphical design and data visualization:

* *Storytelling with Data* by Cole Nussbaumer Knaflic
* *Beyond Bullet Points* by Cliff Atkinson
* *Once Upon an Innovation* by Jean Storlie and Mimi Sherlock
* *Show me the Number: Designing Table and Graphs to Enlighten* by Stephen Few

## Useful R Packages

* `ClustBlock`: hierarchical and partitioning algorithms of blocks of variables. Includes functions for clustering subjects and multivariate analysis of multiblock sensory data, such as Check-All-that-Apply (CLUSCATA), or Free Sorting (CLUSTATIS).
* `ClustVarLV`: functions for the clustering of variables around Latent Variables, for 2-way or 3-way data.
* `corrplot`: provides a visual exploratory tool on correlation matrix that supports automatic variable reordering to help detect hidden patterns among variables. 
* `DistatisR`: implements three-way multidimensional scaling. DiSTATIS is used to analyze multiple distance matrices collected on the same set of observation (e.g., by free sorting).
* `FactoExtra`: makes easy to extract and visualize the output of exploratory multivariate data analyses, including Principal Component Analysis (PCA), Correspondence Analysis (CA), Multiple Correspondence Analysis (MCA), Multiple Factor Analysis (MFA), Hierarchical Clustering (HCKUST) and partioning Clustering (E.g. k-means, PAM,CLARA, etc.)
* `FactoMineR`: dedicated to multivariate Exploratory Data Analysis including Principal Components Analysis (PCA), Correspondence analysis (CA), Multiple Correspondence Analysis (MCA), clustering.
* `rstatix`: a pipe-friendly framework, coherent with the 'tidyverse' design philosophy, for performing basic statistical tests.
* `sensmixed`: to analyze sensory and consumer data within mixed effects model framework.
* `SensoMineR`: dedicated to the statistical analysis of sensory data. It tackles the characterization of the products, panel performance assessment, links between sensory and instrumental data, consumer's preferences, napping evaluation, optimal designs. 
* `SensR`: for Thurstonian Models for sensory discrimination methods, including duotrio, tetrad, triangle, 2-AFC, 3-AFC, A-not A, same-different, 2-AC and degree-of-difference. This package enables the calculation of d-primes, standard errors of d-primes, sample size and power computations, and comparisons of different d-primes.
* `stats`: contains functions for statistical calculations and random number generation. The analysis include ANOVA, posthoc tests, Clustering, Correlation, multivariate analysis, among many others.
* `tempR`: for Analysis and visualization of data from temporal sensory methods, including  temporal check-all-that-apply (TCATA) and temporal dominance of sensation.
