```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```
# Data Visualization {#data-viz}

## Design Principles

## Table Making

## Chart Making

### Philosophy of ggplot2

Explain the principles of multi-layer graphs through an example.

`aes()`, `geom_()`, `theme()`

#### aesthetics

Provide the most relevant options for `aes()`

- x, y, z
- group
- color, fill
- text, label
- alpha, size

#### geom_

Explain the fact that some `geom_()` comes with some stats automatically (e.g. `geom_bar` bins the data)

### Common Charts

#### Scatter points

`geom_point()`

#### Line charts

`geom_line()`, `geom_smooth()`
`geom_abline()`
`geom_hline()` and `geom_vline()`
`geom_segment()` and `geom_arrow()`

#### Bar charts

`geom_bar`, `geom_polygon`, `geom_histogram()`, `geom_freqpoly()`
`position="identity"`, `position="dodge"` or `position="fill"`

#### Distribution

`geom_boxplot()` and `geom_violin()`

#### Text

`geom_text` and `geom_label`
presentation of **{ggrepel}**

#### Rectangles

`geom_tile()`, `geom_rect`, and `geom_raster()`

#### Themes and legend

`theme()`, and pre-defined themes like `theme_bw()`, `theme_minimal()`, etc.
`ggtitle()`
`xlab()`, `ylab()`, or `labs()`

### Additional Topics

#### Playing around with axes

`coord_fixed()`, `coord_cartesian()`, `coord_trans()`
`scale_x_`, `scale_y_`

#### Transposing the plot

`coord_flip()` and `coord_polar()`

#### Splitting plots

`facet_wrap()`, `facet_grid()`

#### Combining plots

**{patchwork}**


