```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# Machine Learning {#machine-learning}
 

## Methods Overview

<!-- ### Unsupervised learning -->

<!-- #### Cluster analysis -->

<!-- Aim of cluster analysis is to discover in high-dimensional data groups of  -->
<!-- observations that are similar to each other in the group and significantly -->
<!-- different from the rest of observations. Common application in consumer science  -->
<!-- is to cluster consumers based on their taste preference to understand and target -->
<!-- specific segments. -->

<!-- #### Factor analysis -->
<!-- #### Principle components analysis -->
<!-- #### t-SNE -->
<!-- ### Semisupervised learning -->
<!-- #### PLS regression -->
<!-- #### Cluster Characterization -->
### Supervised learning

#### Regression

Regression methods approximate the target variable^[This is a bit of simplification. 
In some cases it is some transformation of combination of predictors that 
approximates target variable. An example of this is logistic regression.]
with (usually linear) combination of predictor variables. 

There are multiple regression algorithms varying by type of data they can handle,
type of target variable and additional aspects like ability to perform 
dimensionality reduction. We will take a walk through the ones most relevant for 
sensory and consumer science.

##### Linear regression

The simplest and most popular variant is linear regression in which continuous 
target variable is approximated as linear combination of predictors in a way that 
minimizes sum of squared estimates of errors (SSE). It can be for example used to 
predict consumer liking of a product based on it's sensory profile, but user has
to keep in mind that linear regression can in some cases return value outside 
reasonable range of target values. This can be addressed by capping predictions 
to desired range. Functions in R to apply linear regression are: `lm()` and `glm()`
or `parsnip::linear_reg() %>% parsnip::set_engine("lm")` when using `tidymodels` workflow.

##### Logistic regression

Logistic regression is an algorithm which by use of logistic transformation allows
to apply the same approach as linear regression to cases with binary target variables.
It can be used in R with `glm(family = "binomial")` or
`parsnip::logistic_reg() %>% parsnip::set_engine("glm")` when using `tidymodels` workflow.

##### Penalized regression 

It is often that the data we want to use for modeling have a lot of predictor 
variables, possibly with lot of high correlations. In such cases linear/logistic
regression may become unstable and produce unreasonable predictions. This can be
addressed by use of so called penalized regression. It is a special case where 
instead of minimizing pure error term, algorithm minimizes both error and regression 
coefficients at the same time. This leads to more stable predictions.

There are three variations of penalized regression and all of them can be accessed
via function `glmnet::glmnet()` ($\beta$ is set of regression coefficients and 
$\lambda$ is a parameter to be set by user or determined from cross-validation):

+ Ridge regression (L2 penalty) minimizes $SSE + \lambda \sum|\beta|^2$ and drives
the coefficients to smaller values
+ Lasso regression (L1 penalty) $SSE + \lambda \sum|\beta|$ and forces some of the
coefficients to vanish what can be used for variable selection
+ Elastic-net regression is a combination of the two previous variants 
$SSE + \lambda_1 \sum|\beta| + \lambda_2 \sum|\beta|^2$.

Penalized regression can be also runned in `tidymodels` workflow with 
or `parsnip::linear_reg() %>% parsnip::set_engine("glmnet")`.

##### MARS

One limitation of all mentioned so far methods is that they assume linear relationship
between predictor and target variables. Multivariate adaptive regression spline (MARS)
addresses this by modeling nonlinearities with piecewise linear function. This
gives a nice balance between simplicity and ability to fit complex data, for example
$\Lambda$-shaped once where there is a maximal point from which function decreases 
in both directions. In R this model can be accesed via `earth::earth()` function.

##### PLS

In case of multiple target variables one can apply partial least squares (PLS) regression
which, similarly to PCA looks for components that maximizes explained variance of
the predictors, but at the same time also maximizes their correlation to target variables.
PLS can be applied with `lm()` specifying multiple targets or in `tidymodels` workflow
with `plsmod::pls() %>% parsnip::set_engine("mixOmics")`.

#### K-nearest neighbors

A very simple, yet useful and robust algorithm that works for both numeric and nominal
target variables is K-nearest neighbors. The idea is that for every new observation
we want to predict the algorithms finds K closest points in training set and use
either their mean value (for numeric targets) or most frequent value (for nominal targets)
as prediction. This algorithm can be used with `kknn::kknn()` function or in `tidymodels` workflow
with `parsnip::nearest_neighbor() %>% parsnip::set_engine("kknn")`.

#### Decision trees

Decision tree models the data by splitting the training set in smaller subsets 
in a way that each split is done by a predictor variable so that it maximizes 
the difference in target variable between the subsets. One important advantage 
of decision trees is that they can model complex relationships and interactions
between predictors. To use decision tree in R one can use `rpart::rpart()` or
in `tidymodels` workflow with `parsnip::decision_tree() %>% parsnip::set_engine("rpart")`.

#### Black boxes

So called black boxes are class of models that have too complex structure to directly
interpret relationship between predictor variables and a value predicted by the model.
Their advantage usually is ability to model more complicated data than in case of
interpretable models, but they have greater risk of overfitting (fitting to
noise in training data). Also, lack of clear interpretation may be not acceptable
in some business specific use cases. The later problem can be addressed by use of 
explanation algorithms that will be discussed in later part of this chapter.

##### Random forests

A random forest is a set of decision trees, each one trained on random subset 
of observations and/or predictors. The final prediction is an average of individual
trees' predictions. This way 

##### SVMs
##### Neural networks
##### Computer vision

## Key Topics

### Model Validation

### Interpretability 
#### LIME
#### DALEX
#### IML

## Common Applications
### Predicting sensory profiles from instrumental data
### Predicting consumer response from sensory profiles
### Characterizing consumer clusters

