```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```
# Conclusion and Next Steps {#next-steps}

Congratulations, you've reached the end of this book! 

We hope we have motivated you to continue your amazing journey into the emerging computational sensory science field. To give you a little hand, we will list here list some other resources we would recommend and a summary of the main useful packages for sensory and consumer data analysis/visualization, including the ones we used throughout this book.

## Other Recommended Resources

- **R for Data Science**
- **Analyzing Sensory Data with R**
- **Practical Guide to Cluster Analysis in R**
- **Practical Guide to Principal Component Methods in R**
- **Hands-On Machine Learning with R**
- **Introduction to Statistical and Machine Learning Methods for Data Science**
- **R Graphics Cookbook: Practical Recipes for Visualizing Data**
- **Text Mining with R: A Tidy Approach**
- **Textual Data Science with R**
- **Supervised Machine Learning for Text Analysis in R**

Some interesting book related to story telling, graphical design and data visualization:

- **Storytelling with Data**
- **Beyond Bullet Points**
- **Once Upon an Innovation**
- **Show me the Number: Designing Table and Graphs to Enlighten**

## Useful R Packages in the Sensory and Consumer Science field

- `FactoMineR`: package dedicated to multivariate Exploratory Data Analysis including Principal Components Analysis (PCA), Correspondence analysis (CA), Multiple Correspondence Analysis (MCA), clustering.

- `FactoExtra`: package that makes easy to extract and visualize the output of exploratory multivariate data analyses, including Principal Component Analysis (PCA), Correspondence Analysis (CA), Multiple Correspondence Analysis (MCA), Multiple Factor Analysis (MFA), Hierarchical Clustering (HCKUST) and partioning Clusterins (E.g. k-means, PAM,CLARA, etc.)

- `SensR`: package for Thurstonian Models for sensory discrimination methods, including duotrio, tetrad, triangle, 2-AFC, 3-AFC, A-not A, same-different, 2-AC and degree-of-difference. This package enables the calculation of d-primes, standard errors of d-primes, sample size and power computations, and comparisons of different d-primes.

- `SensoMineR`: package dedicated to the statistical analysis of sensory data. It tackles the characterization of the products, panel performance assessment, links between sensory and instrumental data, consumer's preferences, napping evaluation, optimal designs. 

- `tempR`: package for Analysis and visualization of data from temporal sensory methods, including  temporal check-all-that-apply (TCATA) and temporal dominance of sensation.

- `sensmixed`: package to analyze sensory and consumer data within mixed effects model framework.

- `corrplot`: package that provides a visual exploratory tool on correlation matrix that supports automatic variable reordering to help detect hidden patterns among variables. 

- `stats`: this This package contains functions for statistical calculations and random number generation. The analysis include for instance ANOVA, post hoc tests, Clustering, Correlation, multivariate analysis, among many others.
