# References {-}

Bryan, J. (2018). Happy git and github for the useR. GitHub.  Available from https://happygitwithr.com/
Gillespie, C., & Lovelace, R. (2016). Efficient R programming: A practical guide to smarter programming. " O'Reilly Media, Inc.".
Grolemund, G. Getting Started with R. Rstudio Support. Available from https://support.rstudio.com/hc/en-us/articles/201141096-Getting-Started-with-R
Norman, D. (2013). The design of everyday things: Revised and expanded edition. Basic books.
Peng, R., Caffo, B., & Leek, J. Data Science Specialization [Online course]. Available from https://www.coursera.org/specializations/jhu-data-science
Peng, R., Caffo, B., & Leek, J. Executive data science specialization [Online course]. Available from https://www.coursera.org/specializations/executive-data-science
Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. " O'Reilly Media, Inc.".
Wickham, H. (2016). ggplot2: elegant graphics for data analysis. Springer.
Zuur, A., Ieno, E. N., & Meesters, E. (2009). A Beginner's Guide to R. Springer Science & Business Media.

Breiman, L. (2001). Statistical modeling: The two cultures (with comments and a rejoinder by the author). Statistical science, 16(3), 199-231.
Cleveland, W. S. (2001). Data science: an action plan for expanding the technical areas of the field of statistics. International statistical review, 69(1), 21-26.
Fayyad, U., Piatetsky-Shapiro, G., & Smyth, P. (1996). From data mining to knowledge discovery in databases. AI magazine, 17(3), 37-37.
Naur, P. (1966). The science of datalogy. Communications of the ACM, 9(7), 485.
Tukey, J. W. (1962). The future of data analysis. The annals of mathematical statistics, 33(1), 1-67.
Tukey, J. W. (1977). Exploratory data analysis. Reading, Mass: Addison-Wesley Pub. Co.
Wu, C. F. J. (1997) “Statistics = Data Science?” Lecture notes available online at http://www2.isye.gatech.edu/~jeffwu/presentations/datascience.pdf




