<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Data Analysis | Data Science for Sensory and Consumer Scientists</title>
  <meta name="description" content="Open development of data science book for sensory and consumer scientists.." />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Data Analysis | Data Science for Sensory and Consumer Scientists" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Open development of data science book for sensory and consumer scientists.." />
  <meta name="github-repo" content="john-aigora/i2ds4scc_bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Data Analysis | Data Science for Sensory and Consumer Scientists" />
  
  <meta name="twitter:description" content="Open development of data science book for sensory and consumer scientists.." />
  

<meta name="author" content="Thierry Worch, Julien Delarue, Vanessa Rios de Souza, and John Ennis" />


<meta name="date" content="2022-12-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-prep.html"/>
<link rel="next" href="value-delivery.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>
<link href="libs/tabwid/tabwid.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science for Sensory and Consumer Scientists</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who-should-read-this-book"><i class="fa fa-check"></i>Who Should Read This Book?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-is-this-book-structured"><i class="fa fa-check"></i>How Is This Book Structured</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i>How To Use This Book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="bienvenue.html"><a href="bienvenue.html"><i class="fa fa-check"></i><b>1</b> Bienvenue!</a>
<ul>
<li class="chapter" data-level="1.1" data-path="bienvenue.html"><a href="bienvenue.html#why-data-science-for-sensory-and-consumer-science"><i class="fa fa-check"></i><b>1.1</b> Why Data Science for Sensory and Consumer Science?</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="bienvenue.html"><a href="bienvenue.html#core-principles-in-sensory-and-consumer-science"><i class="fa fa-check"></i><b>1.1.1</b> Core principles in Sensory and Consumer Science</a></li>
<li class="chapter" data-level="1.1.2" data-path="bienvenue.html"><a href="bienvenue.html#computational-sensory-science"><i class="fa fa-check"></i><b>1.1.2</b> Computational Sensory Science</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="start-R.html"><a href="start-R.html"><i class="fa fa-check"></i><b>2</b> Getting Started</a>
<ul>
<li class="chapter" data-level="2.1" data-path="start-R.html"><a href="start-R.html#introduction-to-r"><i class="fa fa-check"></i><b>2.1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="start-R.html"><a href="start-R.html#what-is-r"><i class="fa fa-check"></i><b>2.1.1</b> What is R?</a></li>
<li class="chapter" data-level="2.1.2" data-path="start-R.html"><a href="start-R.html#why-learning-r-or-any-programming-language"><i class="fa fa-check"></i><b>2.1.2</b> Why Learning R (or any Programming Language)?</a></li>
<li class="chapter" data-level="2.1.3" data-path="start-R.html"><a href="start-R.html#why-r"><i class="fa fa-check"></i><b>2.1.3</b> Why R?</a></li>
<li class="chapter" data-level="2.1.4" data-path="start-R.html"><a href="start-R.html#rstudio"><i class="fa fa-check"></i><b>2.1.4</b> Why RStudio/Posit?</a></li>
<li class="chapter" data-level="2.1.5" data-path="start-R.html"><a href="start-R.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>2.1.5</b> Installing R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="start-R.html"><a href="start-R.html#getting-started-in-r"><i class="fa fa-check"></i><b>2.2</b> Getting Started in R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="start-R.html"><a href="start-R.html#packages"><i class="fa fa-check"></i><b>2.2.1</b> Conventions</a></li>
<li class="chapter" data-level="2.2.2" data-path="start-R.html"><a href="start-R.html#install-and-load-packages"><i class="fa fa-check"></i><b>2.2.2</b> Install and Load Packages</a></li>
<li class="chapter" data-level="2.2.3" data-path="start-R.html"><a href="start-R.html#first-analysis-in-r"><i class="fa fa-check"></i><b>2.2.3</b> First Analysis in R</a></li>
<li class="chapter" data-level="2.2.4" data-path="start-R.html"><a href="start-R.html#scripts"><i class="fa fa-check"></i><b>2.2.4</b> R Scripts</a></li>
<li class="chapter" data-level="2.2.5" data-path="start-R.html"><a href="start-R.html#rprojects"><i class="fa fa-check"></i><b>2.2.5</b> Create a Local Project</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="start-R.html"><a href="start-R.html#further-tips-on-how-to-read-this-book"><i class="fa fa-check"></i><b>2.3</b> Further tips on <em>how to read this book?</em></a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="start-R.html"><a href="start-R.html#pipes"><i class="fa fa-check"></i><b>2.3.1</b> Introduction to the <code>{magrittr}</code> and the notion of <em>pipes</em></a></li>
<li class="chapter" data-level="2.3.2" data-path="start-R.html"><a href="start-R.html#tibbles"><i class="fa fa-check"></i><b>2.3.2</b> Tibbles</a></li>
<li class="chapter" data-level="2.3.3" data-path="start-R.html"><a href="start-R.html#calling-variables"><i class="fa fa-check"></i><b>2.3.3</b> Calling Variables</a></li>
<li class="chapter" data-level="2.3.4" data-path="start-R.html"><a href="start-R.html#print-save"><i class="fa fa-check"></i><b>2.3.4</b> Printing vs. Saving results</a></li>
<li class="chapter" data-level="2.3.5" data-path="start-R.html"><a href="start-R.html#running-code-and-handling-errors"><i class="fa fa-check"></i><b>2.3.5</b> Running code and handling errors</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="start-R.html"><a href="start-R.html#git-and-github"><i class="fa fa-check"></i><b>2.4</b> Version Control / Git and GitHub</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="start-R.html"><a href="start-R.html#git"><i class="fa fa-check"></i><b>2.4.1</b> Git</a></li>
<li class="chapter" data-level="2.4.2" data-path="start-R.html"><a href="start-R.html#github"><i class="fa fa-check"></i><b>2.4.2</b> GitHub</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data_science.html"><a href="data_science.html"><i class="fa fa-check"></i><b>3</b> Why Data Science?</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data_science.html"><a href="data_science.html#history-and-definition"><i class="fa fa-check"></i><b>3.1</b> History and Definition</a></li>
<li class="chapter" data-level="3.2" data-path="data_science.html"><a href="data_science.html#benefits-of-data-science"><i class="fa fa-check"></i><b>3.2</b> Benefits of Data Science</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data_science.html"><a href="data_science.html#reproducible-research"><i class="fa fa-check"></i><b>3.2.1</b> Reproducible Research</a></li>
<li class="chapter" data-level="3.2.2" data-path="data_science.html"><a href="data_science.html#standardized-reporting"><i class="fa fa-check"></i><b>3.2.2</b> Standardized Reporting</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data_science.html"><a href="data_science.html#data-scientific-workflow"><i class="fa fa-check"></i><b>3.3</b> Data Scientific Workflow</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data_science.html"><a href="data_science.html#data-collection2"><i class="fa fa-check"></i><b>3.3.1</b> Data Collection</a></li>
<li class="chapter" data-level="3.3.2" data-path="data_science.html"><a href="data_science.html#data-preparation"><i class="fa fa-check"></i><b>3.3.2</b> Data Preparation</a></li>
<li class="chapter" data-level="3.3.3" data-path="data_science.html"><a href="data_science.html#data-analysis2"><i class="fa fa-check"></i><b>3.3.3</b> Data Analysis</a></li>
<li class="chapter" data-level="3.3.4" data-path="data_science.html"><a href="data_science.html#value-delivery2"><i class="fa fa-check"></i><b>3.3.4</b> Value Delivery</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data_science.html"><a href="data_science.html#how-to-learn-data-science"><i class="fa fa-check"></i><b>3.4</b> How to Learn Data Science</a></li>
<li class="chapter" data-level="3.5" data-path="data_science.html"><a href="data_science.html#cautions-dont-that-everybody-does"><i class="fa fa-check"></i><b>3.5</b> Cautions: Don’t that Everybody Does</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-manip.html"><a href="data-manip.html"><i class="fa fa-check"></i><b>4</b> Data Manipulation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-manip.html"><a href="data-manip.html#why-manipulating-data"><i class="fa fa-check"></i><b>4.1</b> Why Manipulating Data?</a></li>
<li class="chapter" data-level="4.2" data-path="data-manip.html"><a href="data-manip.html#tidy-data"><i class="fa fa-check"></i><b>4.2</b> Tidying Data</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="data-manip.html"><a href="data-manip.html#simple-manipulations"><i class="fa fa-check"></i><b>4.2.1</b> Simple Manipulations</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-manip.html"><a href="data-manip.html#pivots"><i class="fa fa-check"></i><b>4.2.2</b> Reshaping Data</a></li>
<li class="chapter" data-level="4.2.3" data-path="data-manip.html"><a href="data-manip.html#transformation-that-alters-the-data"><i class="fa fa-check"></i><b>4.2.3</b> Transformation that Alters the Data</a></li>
<li class="chapter" data-level="4.2.4" data-path="data-manip.html"><a href="data-manip.html#combining-data-from-different-sources"><i class="fa fa-check"></i><b>4.2.4</b> Combining Data from Different Sources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-viz.html"><a href="data-viz.html"><i class="fa fa-check"></i><b>5</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-viz.html"><a href="data-viz.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="data-viz.html"><a href="data-viz.html#design-principles"><i class="fa fa-check"></i><b>5.2</b> Design Principles</a></li>
<li class="chapter" data-level="5.3" data-path="data-viz.html"><a href="data-viz.html#table_making"><i class="fa fa-check"></i><b>5.3</b> Table Making</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data-viz.html"><a href="data-viz.html#flextable"><i class="fa fa-check"></i><b>5.3.1</b> Introduction to <code>{flextable}</code></a></li>
<li class="chapter" data-level="5.3.2" data-path="data-viz.html"><a href="data-viz.html#introdution-to-gt"><i class="fa fa-check"></i><b>5.3.2</b> Introdution to <code>{gt}</code></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="data-viz.html"><a href="data-viz.html#chart-making"><i class="fa fa-check"></i><b>5.4</b> Chart Making</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="data-viz.html"><a href="data-viz.html#philosophy-of-ggplot2"><i class="fa fa-check"></i><b>5.4.1</b> Philosophy of <code>{ggplot2}</code></a></li>
<li class="chapter" data-level="5.4.2" data-path="data-viz.html"><a href="data-viz.html#getting-started-with-ggplot2"><i class="fa fa-check"></i><b>5.4.2</b> Getting started with <code>{ggplot2}</code></a></li>
<li class="chapter" data-level="5.4.3" data-path="data-viz.html"><a href="data-viz.html#common-charts"><i class="fa fa-check"></i><b>5.4.3</b> Common Charts</a></li>
<li class="chapter" data-level="5.4.4" data-path="data-viz.html"><a href="data-viz.html#miscealleneous"><i class="fa fa-check"></i><b>5.4.4</b> Miscealleneous</a></li>
<li class="chapter" data-level="5.4.5" data-path="data-viz.html"><a href="data-viz.html#few-additional-tips-and-tricks"><i class="fa fa-check"></i><b>5.4.5</b> Few Additional Tips and Tricks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="auto-report.html"><a href="auto-report.html"><i class="fa fa-check"></i><b>6</b> Automated Reporting</a>
<ul>
<li class="chapter" data-level="6.1" data-path="auto-report.html"><a href="auto-report.html#what-and-why-automated-reporting"><i class="fa fa-check"></i><b>6.1</b> What and why Automated Reporting?</a></li>
<li class="chapter" data-level="6.2" data-path="auto-report.html"><a href="auto-report.html#integrating-reports-within-analyses-scripts"><i class="fa fa-check"></i><b>6.2</b> Integrating reports within analyses scripts</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="auto-report.html"><a href="auto-report.html#excel"><i class="fa fa-check"></i><b>6.2.1</b> Excel</a></li>
<li class="chapter" data-level="6.2.2" data-path="auto-report.html"><a href="auto-report.html#powerpoint"><i class="fa fa-check"></i><b>6.2.2</b> PowerPoint</a></li>
<li class="chapter" data-level="6.2.3" data-path="auto-report.html"><a href="auto-report.html#word"><i class="fa fa-check"></i><b>6.2.3</b> Word</a></li>
<li class="chapter" data-level="6.2.4" data-path="auto-report.html"><a href="auto-report.html#notes-on-applying-corporate-branding"><i class="fa fa-check"></i><b>6.2.4</b> Notes on applying corporate branding</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="auto-report.html"><a href="auto-report.html#integrating-analyses-scripts-within-your-reporting-tool"><i class="fa fa-check"></i><b>6.3</b> Integrating analyses scripts within your reporting tool</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="auto-report.html"><a href="auto-report.html#what-is-rmarkdown"><i class="fa fa-check"></i><b>6.3.1</b> What is <code>{rmarkdown}</code></a></li>
<li class="chapter" data-level="6.3.2" data-path="auto-report.html"><a href="auto-report.html#starting-with-rmarkdown"><i class="fa fa-check"></i><b>6.3.2</b> Starting with {rmarkdown}</a></li>
<li class="chapter" data-level="6.3.3" data-path="auto-report.html"><a href="auto-report.html#rmarkdown-through-a-simple-example"><i class="fa fa-check"></i><b>6.3.3</b> <code>{rmarkdown}</code> through a Simple Example</a></li>
<li class="chapter" data-level="6.3.4" data-path="auto-report.html"><a href="auto-report.html#creating-a-document-using-knitr"><i class="fa fa-check"></i><b>6.3.4</b> Creating a document using <code>{knitr}</code></a></li>
<li class="chapter" data-level="6.3.5" data-path="auto-report.html"><a href="auto-report.html#example-of-applications"><i class="fa fa-check"></i><b>6.3.5</b> Example of applications</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="auto-report.html"><a href="auto-report.html#to-go-further"><i class="fa fa-check"></i><b>6.4</b> To go further…</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="example-projects.html"><a href="example-projects.html"><i class="fa fa-check"></i><b>7</b> Example Project: The Biscuit Study</a>
<ul>
<li class="chapter" data-level="7.1" data-path="example-projects.html"><a href="example-projects.html#objective-of-the-test"><i class="fa fa-check"></i><b>7.1</b> Objective of the Test</a></li>
<li class="chapter" data-level="7.2" data-path="example-projects.html"><a href="example-projects.html#products"><i class="fa fa-check"></i><b>7.2</b> Products</a></li>
<li class="chapter" data-level="7.3" data-path="example-projects.html"><a href="example-projects.html#consumer-test"><i class="fa fa-check"></i><b>7.3</b> Consumer test</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="example-projects.html"><a href="example-projects.html#participants"><i class="fa fa-check"></i><b>7.3.1</b> Participants</a></li>
<li class="chapter" data-level="7.3.2" data-path="example-projects.html"><a href="example-projects.html#test-design"><i class="fa fa-check"></i><b>7.3.2</b> Test design</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="example-projects.html"><a href="example-projects.html#sensory-descriptive-analysis-data"><i class="fa fa-check"></i><b>7.4</b> Sensory descriptive analysis data</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-collection.html"><a href="data-collection.html"><i class="fa fa-check"></i><b>8</b> Data Collection</a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-collection.html"><a href="data-collection.html#designs-of-sensory-doe-experiments"><i class="fa fa-check"></i><b>8.1</b> Designs of sensory (DoE) experiments</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="data-collection.html"><a href="data-collection.html#general-approach"><i class="fa fa-check"></i><b>8.1.1</b> General approach</a></li>
<li class="chapter" data-level="8.1.2" data-path="data-collection.html"><a href="data-collection.html#Crossover"><i class="fa fa-check"></i><b>8.1.2</b> Crossover designs</a></li>
<li class="chapter" data-level="8.1.3" data-path="data-collection.html"><a href="data-collection.html#BIBD"><i class="fa fa-check"></i><b>8.1.3</b> Balanced incomplete block designs (BIBD)</a></li>
<li class="chapter" data-level="8.1.4" data-path="data-collection.html"><a href="data-collection.html#incomplete-designs-for-hedonic-tests-sensory-informed-designs"><i class="fa fa-check"></i><b>8.1.4</b> Incomplete designs for hedonic tests: Sensory informed designs</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="data-collection.html"><a href="data-collection.html#product-related-designs"><i class="fa fa-check"></i><b>8.2</b> Product-related designs</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="data-collection.html"><a href="data-collection.html#factorial-designs"><i class="fa fa-check"></i><b>8.2.1</b> Factorial designs</a></li>
<li class="chapter" data-level="8.2.2" data-path="data-collection.html"><a href="data-collection.html#mixture-designs"><i class="fa fa-check"></i><b>8.2.2</b> Mixture designs</a></li>
<li class="chapter" data-level="8.2.3" data-path="data-collection.html"><a href="data-collection.html#screening-designs"><i class="fa fa-check"></i><b>8.2.3</b> Screening designs</a></li>
<li class="chapter" data-level="8.2.4" data-path="data-collection.html"><a href="data-collection.html#sensory-informed-designs"><i class="fa fa-check"></i><b>8.2.4</b> Sensory informed designs</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="data-collection.html"><a href="data-collection.html#execute-1"><i class="fa fa-check"></i><b>8.3</b> Execute</a></li>
<li class="chapter" data-level="8.4" data-path="data-collection.html"><a href="data-collection.html#data-import"><i class="fa fa-check"></i><b>8.4</b> Import</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="data-collection.html"><a href="data-collection.html#importing-structured-excel-file"><i class="fa fa-check"></i><b>8.4.1</b> Importing Structured Excel File</a></li>
<li class="chapter" data-level="8.4.2" data-path="data-collection.html"><a href="data-collection.html#importing-unstructured-excel-file"><i class="fa fa-check"></i><b>8.4.2</b> Importing Unstructured Excel File</a></li>
<li class="chapter" data-level="8.4.3" data-path="data-collection.html"><a href="data-collection.html#import-mult-sheet"><i class="fa fa-check"></i><b>8.4.3</b> Importing Data Stored in Multiple Sheets</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="data-prep.html"><a href="data-prep.html"><i class="fa fa-check"></i><b>9</b> Data Preparation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="data-prep.html"><a href="data-prep.html#introduction-1"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="data-prep.html"><a href="data-prep.html#inspect"><i class="fa fa-check"></i><b>9.2</b> Inspect</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="data-prep.html"><a href="data-prep.html#data-inspection"><i class="fa fa-check"></i><b>9.2.1</b> Data Inspection</a></li>
<li class="chapter" data-level="9.2.2" data-path="data-prep.html"><a href="data-prep.html#missing-data"><i class="fa fa-check"></i><b>9.2.2</b> Missing Data</a></li>
<li class="chapter" data-level="9.2.3" data-path="data-prep.html"><a href="data-prep.html#design-inspection"><i class="fa fa-check"></i><b>9.2.3</b> Design Inspection</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="data-prep.html"><a href="data-prep.html#clean"><i class="fa fa-check"></i><b>9.3</b> Clean</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="data-prep.html"><a href="data-prep.html#handling-data-type"><i class="fa fa-check"></i><b>9.3.1</b> Handling Data Type</a></li>
<li class="chapter" data-level="9.3.2" data-path="data-prep.html"><a href="data-prep.html#converting-between-types"><i class="fa fa-check"></i><b>9.3.2</b> Converting between Types</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="data-analysis.html"><a href="data-analysis.html"><i class="fa fa-check"></i><b>10</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="data-analysis.html"><a href="data-analysis.html#sensory-analysis"><i class="fa fa-check"></i><b>10.1</b> Sensory Data</a></li>
<li class="chapter" data-level="10.2" data-path="data-analysis.html"><a href="data-analysis.html#demographic-and-questionnaire-data"><i class="fa fa-check"></i><b>10.2</b> Demographic and Questionnaire Data</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="data-analysis.html"><a href="data-analysis.html#demographic-data-frequency-and-proportion"><i class="fa fa-check"></i><b>10.2.1</b> Demographic Data: Frequency and Proportion</a></li>
<li class="chapter" data-level="10.2.2" data-path="data-analysis.html"><a href="data-analysis.html#eating-behavior-traits-tfeq-data"><i class="fa fa-check"></i><b>10.2.2</b> Eating behavior traits: TFEQ data</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="data-analysis.html"><a href="data-analysis.html#tibble-use"><i class="fa fa-check"></i><b>10.3</b> Consumer Data</a></li>
<li class="chapter" data-level="10.4" data-path="data-analysis.html"><a href="data-analysis.html#combining-sensory-and-consumer-data"><i class="fa fa-check"></i><b>10.4</b> Combining Sensory and Consumer Data</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="data-analysis.html"><a href="data-analysis.html#internal-preference-mapping"><i class="fa fa-check"></i><b>10.4.1</b> Internal Preference Mapping</a></li>
<li class="chapter" data-level="10.4.2" data-path="data-analysis.html"><a href="data-analysis.html#hac"><i class="fa fa-check"></i><b>10.4.2</b> Consumers Clustering</a></li>
<li class="chapter" data-level="10.4.3" data-path="data-analysis.html"><a href="data-analysis.html#drivers-of-liking"><i class="fa fa-check"></i><b>10.4.3</b> Drivers of Liking</a></li>
<li class="chapter" data-level="10.4.4" data-path="data-analysis.html"><a href="data-analysis.html#prefmap"><i class="fa fa-check"></i><b>10.4.4</b> External Preference Mapping</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="value-delivery.html"><a href="value-delivery.html"><i class="fa fa-check"></i><b>11</b> Value Delivery</a>
<ul>
<li class="chapter" data-level="11.1" data-path="value-delivery.html"><a href="value-delivery.html#how-to-communicate"><i class="fa fa-check"></i><b>11.1</b> How to Communicate?</a></li>
<li class="chapter" data-level="11.2" data-path="value-delivery.html"><a href="value-delivery.html#exploratory-explanatory-and-predictive-analysis"><i class="fa fa-check"></i><b>11.2</b> Exploratory, Explanatory and Predictive Analysis</a></li>
<li class="chapter" data-level="11.3" data-path="value-delivery.html"><a href="value-delivery.html#audience-awareness"><i class="fa fa-check"></i><b>11.3</b> Audience Awareness</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="value-delivery.html"><a href="value-delivery.html#technical-audience"><i class="fa fa-check"></i><b>11.3.1</b> Technical Audience</a></li>
<li class="chapter" data-level="11.3.2" data-path="value-delivery.html"><a href="value-delivery.html#management"><i class="fa fa-check"></i><b>11.3.2</b> Management</a></li>
<li class="chapter" data-level="11.3.3" data-path="value-delivery.html"><a href="value-delivery.html#general-interest"><i class="fa fa-check"></i><b>11.3.3</b> General Interest</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="value-delivery.html"><a href="value-delivery.html#methods-to-communicate"><i class="fa fa-check"></i><b>11.4</b> Methods to Communicate</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="value-delivery.html"><a href="value-delivery.html#consider-the-mechanism"><i class="fa fa-check"></i><b>11.4.1</b> Consider the Mechanism</a></li>
<li class="chapter" data-level="11.4.2" data-path="value-delivery.html"><a href="value-delivery.html#pick-the-correct-format"><i class="fa fa-check"></i><b>11.4.2</b> Pick the Correct Format</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="value-delivery.html"><a href="value-delivery.html#storytelling"><i class="fa fa-check"></i><b>11.5</b> Storytelling</a></li>
<li class="chapter" data-level="11.6" data-path="value-delivery.html"><a href="value-delivery.html#reformulate2"><i class="fa fa-check"></i><b>11.6</b> Reformulate</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>12</b> Machine Learning</a>
<ul>
<li class="chapter" data-level="12.1" data-path="machine-learning.html"><a href="machine-learning.html#introduction-2"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="machine-learning.html"><a href="machine-learning.html#introduction-of-the-data"><i class="fa fa-check"></i><b>12.2</b> Introduction of the Data</a></li>
<li class="chapter" data-level="12.3" data-path="machine-learning.html"><a href="machine-learning.html#machine-learning-methods"><i class="fa fa-check"></i><b>12.3</b> Machine Learning Methods</a></li>
<li class="chapter" data-level="12.4" data-path="machine-learning.html"><a href="machine-learning.html#unsupervised-machine-learning"><i class="fa fa-check"></i><b>12.4</b> Unsupervised Machine learning</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="machine-learning.html"><a href="machine-learning.html#dimensionality-reduction"><i class="fa fa-check"></i><b>12.4.1</b> Dimensionality Reduction</a></li>
<li class="chapter" data-level="12.4.2" data-path="machine-learning.html"><a href="machine-learning.html#clustering"><i class="fa fa-check"></i><b>12.4.2</b> Clustering</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="machine-learning.html"><a href="machine-learning.html#supervised-learning"><i class="fa fa-check"></i><b>12.5</b> Supervised learning</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="machine-learning.html"><a href="machine-learning.html#workflow"><i class="fa fa-check"></i><b>12.5.1</b> Workflow</a></li>
<li class="chapter" data-level="12.5.2" data-path="machine-learning.html"><a href="machine-learning.html#regression"><i class="fa fa-check"></i><b>12.5.2</b> Regression</a></li>
<li class="chapter" data-level="12.5.3" data-path="machine-learning.html"><a href="machine-learning.html#other-common-supervised-ml-algorithms"><i class="fa fa-check"></i><b>12.5.3</b> Other common Supervised ML algorithms</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="machine-learning.html"><a href="machine-learning.html#practical-guide-to-supervised-machine-learning"><i class="fa fa-check"></i><b>12.6</b> Practical Guide to Supervised Machine Learning</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="machine-learning.html"><a href="machine-learning.html#introduction-to-the-tidymodels-framework"><i class="fa fa-check"></i><b>12.6.1</b> Introduction to the <code>{tidymodels}</code> framework</a></li>
<li class="chapter" data-level="12.6.2" data-path="machine-learning.html"><a href="machine-learning.html#sampling-the-data"><i class="fa fa-check"></i><b>12.6.2</b> Sampling the data</a></li>
<li class="chapter" data-level="12.6.3" data-path="machine-learning.html"><a href="machine-learning.html#cross-validation"><i class="fa fa-check"></i><b>12.6.3</b> Cross Validation</a></li>
<li class="chapter" data-level="12.6.4" data-path="machine-learning.html"><a href="machine-learning.html#data-preprocessing-recipes"><i class="fa fa-check"></i><b>12.6.4</b> Data Preprocessing <code>{recipes}</code></a></li>
<li class="chapter" data-level="12.6.5" data-path="machine-learning.html"><a href="machine-learning.html#model-definition"><i class="fa fa-check"></i><b>12.6.5</b> Model definition</a></li>
<li class="chapter" data-level="12.6.6" data-path="machine-learning.html"><a href="machine-learning.html#set-the-whole-process-into-a-workflow"><i class="fa fa-check"></i><b>12.6.6</b> Set the whole Process into a workflow</a></li>
<li class="chapter" data-level="12.6.7" data-path="machine-learning.html"><a href="machine-learning.html#tuning-the-parameters"><i class="fa fa-check"></i><b>12.6.7</b> Tuning the parameters</a></li>
<li class="chapter" data-level="12.6.8" data-path="machine-learning.html"><a href="machine-learning.html#model-training"><i class="fa fa-check"></i><b>12.6.8</b> Model training</a></li>
<li class="chapter" data-level="12.6.9" data-path="machine-learning.html"><a href="machine-learning.html#model-evaluation"><i class="fa fa-check"></i><b>12.6.9</b> Model evaluation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="text-analysis.html"><a href="text-analysis.html"><i class="fa fa-check"></i><b>13</b> Text Analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="text-analysis.html"><a href="text-analysis.html#introduction-to-natural-language-processing"><i class="fa fa-check"></i><b>13.1</b> Introduction to Natural Language Processing</a></li>
<li class="chapter" data-level="13.2" data-path="text-analysis.html"><a href="text-analysis.html#application-of-text-analysis-in-sensory-and-consumer-science"><i class="fa fa-check"></i><b>13.2</b> Application of Text Analysis in Sensory and Consumer Science</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="text-analysis.html"><a href="text-analysis.html#text-analysis-as-way-to-describe-products"><i class="fa fa-check"></i><b>13.2.1</b> Text analysis as way to describe products</a></li>
<li class="chapter" data-level="13.2.2" data-path="text-analysis.html"><a href="text-analysis.html#objectives-of-text-analysis"><i class="fa fa-check"></i><b>13.2.2</b> Objectives of Text Analysis</a></li>
<li class="chapter" data-level="13.2.3" data-path="text-analysis.html"><a href="text-analysis.html#classical-text-analysis-workflow"><i class="fa fa-check"></i><b>13.2.3</b> Classical <em>text analysis</em> workflow</a></li>
<li class="chapter" data-level="13.2.4" data-path="text-analysis.html"><a href="text-analysis.html#warnings"><i class="fa fa-check"></i><b>13.2.4</b> Warnings</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="text-analysis.html"><a href="text-analysis.html#illustration-using-sorting-task-data"><i class="fa fa-check"></i><b>13.3</b> Illustration using Sorting Task Data</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="text-analysis.html"><a href="text-analysis.html#data-pre-processing"><i class="fa fa-check"></i><b>13.3.1</b> Data Pre-processing</a></li>
<li class="chapter" data-level="13.3.2" data-path="text-analysis.html"><a href="text-analysis.html#introduction-to-working-with-strings-stringr"><i class="fa fa-check"></i><b>13.3.2</b> Introduction to working with strings (<code>{stringr}</code>)</a></li>
<li class="chapter" data-level="13.3.3" data-path="text-analysis.html"><a href="text-analysis.html#tokenization"><i class="fa fa-check"></i><b>13.3.3</b> Tokenization</a></li>
<li class="chapter" data-level="13.3.4" data-path="text-analysis.html"><a href="text-analysis.html#simple-transformations"><i class="fa fa-check"></i><b>13.3.4</b> Simple Transformations</a></li>
<li class="chapter" data-level="13.3.5" data-path="text-analysis.html"><a href="text-analysis.html#splitting-further-the-tokens"><i class="fa fa-check"></i><b>13.3.5</b> Splitting further the tokens</a></li>
<li class="chapter" data-level="13.3.6" data-path="text-analysis.html"><a href="text-analysis.html#stopwords"><i class="fa fa-check"></i><b>13.3.6</b> Stopwords</a></li>
<li class="chapter" data-level="13.3.7" data-path="text-analysis.html"><a href="text-analysis.html#stemming-and-lemmatization"><i class="fa fa-check"></i><b>13.3.7</b> Stemming and Lemmatization</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="text-analysis.html"><a href="text-analysis.html#text-analysis-1"><i class="fa fa-check"></i><b>13.4</b> Text Analysis</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="text-analysis.html"><a href="text-analysis.html#raw-frequencies-and-visualization"><i class="fa fa-check"></i><b>13.4.1</b> Raw Frequencies and Visualization</a></li>
<li class="chapter" data-level="13.4.2" data-path="text-analysis.html"><a href="text-analysis.html#bigrams-n-grams"><i class="fa fa-check"></i><b>13.4.2</b> Bigrams, <em>n</em>-grams</a></li>
<li class="chapter" data-level="13.4.3" data-path="text-analysis.html"><a href="text-analysis.html#word-embedding"><i class="fa fa-check"></i><b>13.4.3</b> Word Embedding</a></li>
<li class="chapter" data-level="13.4.4" data-path="text-analysis.html"><a href="text-analysis.html#sentiment-analysis"><i class="fa fa-check"></i><b>13.4.4</b> Sentiment Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="text-analysis.html"><a href="text-analysis.html#to-go-further-1"><i class="fa fa-check"></i><b>13.5</b> To go further…</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="dashboards.html"><a href="dashboards.html"><i class="fa fa-check"></i><b>14</b> Dashboards</a>
<ul>
<li class="chapter" data-level="14.1" data-path="dashboards.html"><a href="dashboards.html#objectives"><i class="fa fa-check"></i><b>14.1</b> Objectives</a></li>
<li class="chapter" data-level="14.2" data-path="dashboards.html"><a href="dashboards.html#introduction-to-shiny-through-an-example"><i class="fa fa-check"></i><b>14.2</b> Introduction to Shiny through an Example</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="dashboards.html"><a href="dashboards.html#what-is-a-shiny-application"><i class="fa fa-check"></i><b>14.2.1</b> What is a Shiny application?</a></li>
<li class="chapter" data-level="14.2.2" data-path="dashboards.html"><a href="dashboards.html#starting-with-shiny"><i class="fa fa-check"></i><b>14.2.2</b> Starting with Shiny</a></li>
<li class="chapter" data-level="14.2.3" data-path="dashboards.html"><a href="dashboards.html#illustration"><i class="fa fa-check"></i><b>14.2.3</b> Illustration</a></li>
<li class="chapter" data-level="14.2.4" data-path="dashboards.html"><a href="dashboards.html#deploying-the-application"><i class="fa fa-check"></i><b>14.2.4</b> Deploying the Application</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="dashboards.html"><a href="dashboards.html#to-go-further-2"><i class="fa fa-check"></i><b>14.3</b> To go further…</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="dashboards.html"><a href="dashboards.html#personalizing-and-tuning-your-application"><i class="fa fa-check"></i><b>14.3.1</b> Personalizing and Tuning your application</a></li>
<li class="chapter" data-level="14.3.2" data-path="dashboards.html"><a href="dashboards.html#upgrading-tables"><i class="fa fa-check"></i><b>14.3.2</b> Upgrading Tables</a></li>
<li class="chapter" data-level="14.3.3" data-path="dashboards.html"><a href="dashboards.html#building-dashboard"><i class="fa fa-check"></i><b>14.3.3</b> Building Dashboard</a></li>
<li class="chapter" data-level="14.3.4" data-path="dashboards.html"><a href="dashboards.html#interactive-graphics"><i class="fa fa-check"></i><b>14.3.4</b> Interactive Graphics</a></li>
<li class="chapter" data-level="14.3.5" data-path="dashboards.html"><a href="dashboards.html#interactive-documents"><i class="fa fa-check"></i><b>14.3.5</b> Interactive Documents</a></li>
<li class="chapter" data-level="14.3.6" data-path="dashboards.html"><a href="dashboards.html#documentation-and-books"><i class="fa fa-check"></i><b>14.3.6</b> Documentation and Books</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="next-steps.html"><a href="next-steps.html"><i class="fa fa-check"></i><b>15</b> Conclusion and Next Steps</a>
<ul>
<li class="chapter" data-level="15.1" data-path="next-steps.html"><a href="next-steps.html#other-recommended-resources"><i class="fa fa-check"></i><b>15.1</b> Other Recommended Resources</a></li>
<li class="chapter" data-level="15.2" data-path="next-steps.html"><a href="next-steps.html#useful-r-packages"><i class="fa fa-check"></i><b>15.2</b> Useful R Packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for Sensory and Consumer Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-analysis" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> Data Analysis<a href="data-analysis.html#data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<blockquote>
<p>Although the data-science workflow suggests a clear separation between data manipulation and data analysis, in practice such separation is not that obvious. Indeed, most analyses require data manipulation. In fact, some data transformation can be seen as a part of both data transformation and data analysis. Yet, this Section is somewhat more dedicated to the analysis of data, by 1) presenting how some of the most common analyses in sensory and consumer reserach are performed, 2) integrating the analysis part to your script, and most importantly 3) providing applications and alternatives or extension to all the procedures presented in <a href="data-manip.html#data-manip">4</a> and in <a href="data-viz.html#data-viz">5</a>. With that in mind, the emphasis is not on the results and interpretation of the results, but on the path to get such results.
For practical reasons, this chapter is divided in 3 sub-sections, one dedicated to the sensory data, one to the consumer data, and one combining both.</p>
</blockquote>
<div id="sensory-analysis" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Sensory Data<a href="data-analysis.html#sensory-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As one may expect, this chapter is mostly built around the <code>{tidyverse}</code>:</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="data-analysis.html#cb339-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb339-2"><a href="data-analysis.html#cb339-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb339-3"><a href="data-analysis.html#cb339-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code></pre></div>
<p>Let’s start with the analysis of our sensory data stored in <em>biscuits_sensory_profile.xlsx</em>.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="data-analysis.html#cb340-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;biscuits_sensory_profile.xlsx&quot;</span>)</span>
<span id="cb340-2"><a href="data-analysis.html#cb340-2" aria-hidden="true" tabindex="-1"></a>p_info <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Product Info&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb340-3"><a href="data-analysis.html#cb340-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Type)</span>
<span id="cb340-4"><a href="data-analysis.html#cb340-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb340-5"><a href="data-analysis.html#cb340-5" aria-hidden="true" tabindex="-1"></a>sensory <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Data&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb340-6"><a href="data-analysis.html#cb340-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(p_info, <span class="at">by =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb340-7"><a href="data-analysis.html#cb340-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(Protein<span class="sc">:</span>Fiber, <span class="at">.after =</span> Product)</span></code></pre></div>
<p>Typically, sensory scientists first seek to determine whether there are differences between samples for the different attributes. This is done through Analysis of Variance (ANOVA) and can be done using the <code>lm()</code> or <code>aov()</code> functions.</p>
<p>Let’s start by running the ANOVA for the attribute <code>Sweet</code>. Since the test has not been duplicated, the 2-way ANOVA (including the Product and Assessor effects) without interaction is used. This is done using the following code:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="data-analysis.html#cb341-1" aria-hidden="true" tabindex="-1"></a>sweet_aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sweet <span class="sc">~</span> Product <span class="sc">+</span> Judge, <span class="at">data =</span> sensory)</span>
<span id="cb341-2"><a href="data-analysis.html#cb341-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(sweet_aov)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Sweet
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## Product   10   2654     265    7.27 4.5e-08 ***
## Judge      8   4451     556   15.25 2.3e-13 ***
## Residuals 80   2918      36                    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>The results provided here by <code>anova()</code> are not handy to manipulate as the output is not stored in a matrix or data frame. Instead, and as illustrated later, we apply the <code>tidy()</code> function from <code>{broom}</code> as it tidies the statistical outputs from most testing/modelling functions into a user-friendly tibble.</p>
</blockquote>
<p>We could duplicate this code for each single attribute, but this would be quite tedious for large number of attributes. Moreover, this code is sensitive to the way the variables are named, and hence might not be suitable for other data sets. Instead, we propose two solutions, one using <code>split()</code> combined with <code>map()</code> and one involving <code>nest_by()</code> to run this analysis automatically.</p>
<p>For both these solutions, the data should be stored in the long and thin form, which can be obtained using <code>pivot_longer()</code>:</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="data-analysis.html#cb343-1" aria-hidden="true" tabindex="-1"></a>senso_aov_data <span class="ot">&lt;-</span> sensory <span class="sc">%&gt;%</span></span>
<span id="cb343-2"><a href="data-analysis.html#cb343-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(Shiny<span class="sc">:</span>Melting, <span class="at">names_to =</span> <span class="st">&quot;Attribute&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Score&quot;</span>)</span></code></pre></div>
<p>From this structure, the first approach consists in splitting the data by attribute. Once done, we run the ANOVA for each subset (the model is then defined as <code>Score ~ Product + Judge</code>) automatically using <code>map()</code><a href="#fn44" class="footnote-ref" id="fnref44"><sup>44</sup></a>, and we extract the results of interest using the <code>{broom}</code> package.</p>
<p>Ultimately, the results can be combined again using <code>enframe()</code> and <code>unnest()</code>.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="data-analysis.html#cb344-1" aria-hidden="true" tabindex="-1"></a>senso_aov1 <span class="ot">&lt;-</span> senso_aov_data <span class="sc">%&gt;%</span></span>
<span id="cb344-2"><a href="data-analysis.html#cb344-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">split</span>(.<span class="sc">$</span>Attribute) <span class="sc">%&gt;%</span></span>
<span id="cb344-3"><a href="data-analysis.html#cb344-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="cf">function</span>(data) {</span>
<span id="cb344-4"><a href="data-analysis.html#cb344-4" aria-hidden="true" tabindex="-1"></a>    res <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">anova</span>(<span class="fu">lm</span>(Score <span class="sc">~</span> Product <span class="sc">+</span> Judge, <span class="at">data =</span> data)))</span>
<span id="cb344-5"><a href="data-analysis.html#cb344-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(res)</span>
<span id="cb344-6"><a href="data-analysis.html#cb344-6" aria-hidden="true" tabindex="-1"></a>  }) <span class="sc">%&gt;%</span></span>
<span id="cb344-7"><a href="data-analysis.html#cb344-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">enframe</span>(<span class="at">name =</span> <span class="st">&quot;Attribute&quot;</span>, <span class="at">value =</span> <span class="st">&quot;res&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb344-8"><a href="data-analysis.html#cb344-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(res)</span></code></pre></div>
<p>The second approach uses the advantage of tibbles and nests the analysis by attribute (meaning the analysis is done for each attribute separately, a bit like <code>group_by()</code>). In this case, we store the results of the ANOVA in a new variable called <code>mod</code>.</p>
<p>Once the analysis is done, we summarize the info stored in <code>mod</code> by converting it into a tibble using <code>{broom}</code>:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="data-analysis.html#cb345-1" aria-hidden="true" tabindex="-1"></a>senso_aov2 <span class="ot">&lt;-</span> senso_aov_data <span class="sc">%&gt;%</span></span>
<span id="cb345-2"><a href="data-analysis.html#cb345-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest_by</span>(Attribute) <span class="sc">%&gt;%</span></span>
<span id="cb345-3"><a href="data-analysis.html#cb345-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mod =</span> <span class="fu">list</span>(<span class="fu">lm</span>(Score <span class="sc">~</span> Product <span class="sc">+</span> Judge, <span class="at">data =</span> data))) <span class="sc">%&gt;%</span></span>
<span id="cb345-4"><a href="data-analysis.html#cb345-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">anova</span>(mod))) <span class="sc">%&gt;%</span></span>
<span id="cb345-5"><a href="data-analysis.html#cb345-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Attribute&#39;. You
## can override using the `.groups` argument.</code></pre>
<p>The two approaches return the exact same results:</p>
<pre><code>## # A tibble: 96 × 7
##    Attribute term     df sumsq meansq stati…¹   p.value
##    &lt;chr&gt;     &lt;chr&gt; &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
##  1 Astringe… Prod…    10  870.   87.0    1.62  1.16e- 1
##  2 Astringe… Judge     8 5041.  630.    11.7   6.94e-11
##  3 Astringe… Resi…    80 4302.   53.8   NA    NA       
##  4 Bitter    Prod…    10 1005.  101.     3.95  2.11e- 4
##  5 Bitter    Judge     8 2863.  358.    14.1   1.42e-12
##  6 Bitter    Resi…    80 2034.   25.4   NA    NA       
##  7 Brittle   Prod…    10 6246.  625.    11.0   1.42e-11
##  8 Brittle   Judge     8 4243.  530.     9.38  4.86e- 9
##  9 Brittle   Resi…    80 4525.   56.6   NA    NA       
## 10 Cereal f… Prod…    10  795.   79.5    1.22  2.94e- 1
## # … with 86 more rows, and abbreviated variable name
## #   ¹​statistic</code></pre>
<p>Let’s dig into the results by extracting the attributes that do not show significant differences at 5%. Since the <code>tidy()</code> function from <code>{broom}</code> tidies the data into a tibble, all the usual data transformation can be performed. Let’s filter only the <code>Product</code> effect under <code>term</code>, and let’s order the <code>p.value</code> decreasingly:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="data-analysis.html#cb348-1" aria-hidden="true" tabindex="-1"></a>res_aov <span class="ot">&lt;-</span> senso_aov1 <span class="sc">%&gt;%</span></span>
<span id="cb348-2"><a href="data-analysis.html#cb348-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb348-3"><a href="data-analysis.html#cb348-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Attribute, statistic, p.value) <span class="sc">%&gt;%</span></span>
<span id="cb348-4"><a href="data-analysis.html#cb348-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(p.value)) <span class="sc">%&gt;%</span></span>
<span id="cb348-5"><a href="data-analysis.html#cb348-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p.value =</span> <span class="fu">round</span>(p.value, <span class="dv">3</span>))</span></code></pre></div>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="data-analysis.html#cb349-1" aria-hidden="true" tabindex="-1"></a>res_aov <span class="sc">%&gt;%</span></span>
<span id="cb349-2"><a href="data-analysis.html#cb349-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p.value <span class="sc">&gt;=</span> <span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   Attribute     statistic p.value
##   &lt;chr&gt;             &lt;dbl&gt;   &lt;dbl&gt;
## 1 Cereal flavor      1.22   0.294
## 2 Roasted odor       1.40   0.193
## 3 Astringent         1.62   0.116
## 4 Sticky             1.67   0.101</code></pre>
<p>As can be seen, the products do not show any significant differences at 5% for 4 attributes: <code>Cereal flavor</code> (p=0.294), <code>Roasted odor</code> (p=0.193), <code>Astringent</code> (p=0.116), and <code>Sticky</code> (p=0.101).</p>
<p>Rather than showing the results in a table, let’s visualize them graphically as a bar-chart by representing the F-values. The attributes are ordered decreasingly, and colour-coded based on their significance:</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="data-analysis.html#cb351-1" aria-hidden="true" tabindex="-1"></a>res_aov <span class="sc">%&gt;%</span></span>
<span id="cb351-2"><a href="data-analysis.html#cb351-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Signif =</span> <span class="fu">ifelse</span>(p.value <span class="sc">&lt;=</span> <span class="fl">0.05</span>, <span class="st">&quot;Signif.&quot;</span>, <span class="st">&quot;Not Signif.&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb351-3"><a href="data-analysis.html#cb351-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Signif =</span> <span class="fu">factor</span>(Signif, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Signif.&quot;</span>, <span class="st">&quot;Not Signif.&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb351-4"><a href="data-analysis.html#cb351-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Attribute, statistic), <span class="at">y =</span> statistic, <span class="at">fill =</span> Signif)) <span class="sc">+</span></span>
<span id="cb351-5"><a href="data-analysis.html#cb351-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb351-6"><a href="data-analysis.html#cb351-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Signif.&quot;</span> <span class="ot">=</span> <span class="st">&quot;forestgreen&quot;</span>, <span class="st">&quot;Not Signif.&quot;</span> <span class="ot">=</span> <span class="st">&quot;orangered2&quot;</span>)) <span class="sc">+</span></span>
<span id="cb351-7"><a href="data-analysis.html#cb351-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Sensory Attributes&quot;</span>, <span class="st">&quot;(The attributes are sorted according to product-wise F-values)&quot;</span>) <span class="sc">+</span></span>
<span id="cb351-8"><a href="data-analysis.html#cb351-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb351-9"><a href="data-analysis.html#cb351-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb351-10"><a href="data-analysis.html#cb351-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;F-values&quot;</span>) <span class="sc">+</span></span>
<span id="cb351-11"><a href="data-analysis.html#cb351-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-244-1.png" width="672" /></p>
<p>It appears that the evaluated biscuits differ the most (top 5) for <code>Initial hardness</code>, <code>Shiny</code>, <code>Dairy flavor</code>, <code>External color intensity</code>, and <code>Thickness</code>.</p>
<blockquote>
<p>As an alternative, the <code>decat()</code> function from the <code>{SensoMineR}</code> package would do the same job, as it automatically performs ANOVA on a set of attributes (presented in subsequent columns). Additionally, it also perform some t-tests that highlight which samples are significantly more (or less) intense than average for each attribute.</p>
</blockquote>
<p>Once the significant differences have been checked, a follow-up analysis consists in visualizing these differences in a multivariate way. Such visualization is often done through Principal Component Analysis (PCA). In practice, PCA is performed on the sensory profiles. Let’s start with building such table:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="data-analysis.html#cb352-1" aria-hidden="true" tabindex="-1"></a>senso_mean <span class="ot">&lt;-</span> sensory <span class="sc">%&gt;%</span></span>
<span id="cb352-2"><a href="data-analysis.html#cb352-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(Shiny<span class="sc">:</span>Melting, <span class="at">names_to =</span> <span class="st">&quot;Attribute&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Score&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb352-3"><a href="data-analysis.html#cb352-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Judge) <span class="sc">%&gt;%</span></span>
<span id="cb352-4"><a href="data-analysis.html#cb352-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Attribute, <span class="at">values_from =</span> Score, <span class="at">values_fn =</span> mean)</span></code></pre></div>
<p>Such table is then submitted to PCA. R proposes many solutions to run such analysis, including the <code>prcomp()</code> and <code>princomp()</code> functions from the <code>{stats}</code> package. However, we prefer to use <code>PCA()</code> from the <code>{FactoMineR}</code> as it is more complete as it proposes many options that are very useful in sensory and consumer research (e.g. it generates the graphics automatically, and allows projecting supplementary individuals and/or variables).</p>
<p>It should however be noted that the <code>PCA()</code> function does not accept tibbles. Instead, the table should be stored in a matrix or data frame which contain the individuals’ names (here the product names) as row names. Fortunately, there is an easy solution that allows converting a tibble into a data frame (<code>as.data.frame()</code>) and passing the <code>Product</code> column into row names (<code>column_to_rownames(var="Product")</code>).</p>
<p>Since the data also contain two qualitative variables in <code>Protein</code> and <code>Fiber</code>, they should either be removed prior to running the analysis, or better be projected as supplementary through the <code>quali.sup</code> parameter from <code>PCA()</code>. Finally, since <code>POpt</code> is an optimized product, let’s not include it in the analysis per se (it is not contributing to the construction of the dimensions). Instead we project it as supplementary (through <code>ind.sup</code>) to illustrate where it would be located on the space if it were.</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="data-analysis.html#cb353-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FactoMineR)</span>
<span id="cb353-2"><a href="data-analysis.html#cb353-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb353-3"><a href="data-analysis.html#cb353-3" aria-hidden="true" tabindex="-1"></a>senso_pca <span class="ot">&lt;-</span> senso_mean <span class="sc">%&gt;%</span></span>
<span id="cb353-4"><a href="data-analysis.html#cb353-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Product) <span class="sc">%&gt;%</span></span>
<span id="cb353-5"><a href="data-analysis.html#cb353-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb353-6"><a href="data-analysis.html#cb353-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb353-7"><a href="data-analysis.html#cb353-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">PCA</span>(., <span class="at">ind.sup =</span> <span class="fu">nrow</span>(.), <span class="at">quali.sup =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">graph =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Since we set the option <code>graph=FALSE</code>, the PCA plots are not yet being generated. Although <code>PCA()</code> can generate the plots either in <code>{base}</code> R language, or in <code>{ggplot2}</code>, we prefer to use a complementary package called <code>{factoextra}</code> which re-creates most plots from <code>{FactoMineR}</code> (and some other packages) as a <code>ggplot()</code> object. This comes in very handy as you can benefit from the flexibility offered by <code>ggplot()</code>.</p>
<p>The score map (the product map) from <code>PCA()</code> is created trough <code>fviz_pca_ind()</code>, whereas the variables’ representation is created with <code>fviz_pca_var()</code>. <code>fviz_pca_biplot()</code> is used to produce the so-called <em>biplot</em>.</p>
<p>To illustrate this, let’s reproduce the product map by coloring the products using the supplementary variables (<code>Protein</code> and <code>Fiber</code> content). This can easily be done through the <code>habillage</code> parameter from <code>fviz_pca_ind()</code>, which can either take a numerical value (position) of the name of the qualitative variable.</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="data-analysis.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb354-2"><a href="data-analysis.html#cb354-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb354-3"><a href="data-analysis.html#cb354-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(senso_pca, <span class="at">habillage =</span> <span class="st">&quot;Protein&quot;</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>)</span>
<span id="cb354-4"><a href="data-analysis.html#cb354-4" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(senso_pca, <span class="at">habillage =</span> <span class="dv">2</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>)</span>
<span id="cb354-5"><a href="data-analysis.html#cb354-5" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(senso_pca)</span>
<span id="cb354-6"><a href="data-analysis.html#cb354-6" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_biplot</span>(senso_pca)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-249-1.png" width="672" /></p>
<p>Here, <code>repel=TRUE</code> uses <code>geom_text_repel()</code> from <code>{ggrepel}</code> (rather than <code>geom_text()</code> from <code>{ggplot2}</code>) to avoid having labels overlapping.</p>
<p>On the first dimension, <code>P10</code> is opposed to <code>P09</code> and <code>P03</code> as it is more intense for attributes such as <code>Sweet</code>, and <code>Dairy flavor</code> for example, and less intense for attributes such as <code>Dry in mouth</code> and <code>External color intensity</code>. On the second dimension, <code>P08</code>and <code>P06</code> are opposed to <code>P02</code> and <code>P07</code> as they score higher for <code>Qty of inclusions</code>, and <code>Initial hardness</code>, and score lower for <code>RawDough flavor</code> and <code>Shiny</code>. <code>POpt</code> is located between <code>P05</code> and <code>P06</code>.</p>
<blockquote>
<p>Many more visualizations can be produced. Amongst others, let’s mention:
* Scree plot showing the evolution of the eigenvalues across dimensions to help decide how many dimensions to consider;
* The representation of the product space on other dimensions (by default, dimension 1 and dimension 2 are shown);
* Representations of the (product or attribute) space in which the contribution or quality of representation of the elements are showcased.</p>
</blockquote>
<p>For more information regarding the various options offered by <code>{factoextra}</code>, see (REF BOOK <code>{factoextra}</code>).</p>
</div>
<div id="demographic-and-questionnaire-data" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Demographic and Questionnaire Data<a href="data-analysis.html#demographic-and-questionnaire-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <em>biscuits_traits.xlsx</em> file contains descriptive (i.e. <em>demographic</em>) information regarding the consumers and their food-related behavioral traits (i.e. psychometric <em>TFEQ</em> data, see Section <a href="example-projects.html#example-projects">7</a> for more information). This file has three tabs denoted as <em>Data</em>, <em>Variables</em>, and <em>Levels</em>:</p>
<ul>
<li><em>Data</em> contains the data, which is coded;</li>
<li><em>Variables</em> provides information (e.g. name, information) related to the different variables present in <em>Data</em>;</li>
<li><em>Levels</em> provides information about the different levels each variable can take.</li>
</ul>
<p>Let’s start with importing this data set. The importation is done in multiple steps as following:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="data-analysis.html#cb355-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;biscuits_traits.xlsx&quot;</span>)</span>
<span id="cb355-2"><a href="data-analysis.html#cb355-2" aria-hidden="true" tabindex="-1"></a><span class="fu">excel_sheets</span>(file_path)</span></code></pre></div>
<pre><code>## [1] &quot;Data&quot;      &quot;Variables&quot; &quot;Levels&quot;</code></pre>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="data-analysis.html#cb357-1" aria-hidden="true" tabindex="-1"></a>demo_var <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Variables&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb357-2"><a href="data-analysis.html#cb357-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Code, Name)</span>
<span id="cb357-3"><a href="data-analysis.html#cb357-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb357-4"><a href="data-analysis.html#cb357-4" aria-hidden="true" tabindex="-1"></a>demo_lev <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Levels&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb357-5"><a href="data-analysis.html#cb357-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Question, Code, Levels) <span class="sc">%&gt;%</span></span>
<span id="cb357-6"><a href="data-analysis.html#cb357-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(demo_var, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;Question&quot;</span> <span class="ot">=</span> <span class="st">&quot;Code&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb357-7"><a href="data-analysis.html#cb357-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Question)</span>
<span id="cb357-8"><a href="data-analysis.html#cb357-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb357-9"><a href="data-analysis.html#cb357-9" aria-hidden="true" tabindex="-1"></a>demographic <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Data&quot;</span>, <span class="at">skip =</span> <span class="dv">1</span>, <span class="at">col_names =</span> <span class="fu">unlist</span>(demo_var<span class="sc">$</span>Name))</span></code></pre></div>
<div id="demographic-data-frequency-and-proportion" class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Demographic Data: Frequency and Proportion<a href="data-analysis.html#demographic-data-frequency-and-proportion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this demographic data file, let’s start by having a look at the partition of consumers for each of the descriptive variables. This is done by computing the frequency and proportion (in percentage) attached to each level of <code>Living area</code>, <code>Housing</code>, <code>Income range</code>, and <code>Occupation</code>. To obtain such a table, let’s start by selecting only the columns corresponding to these variables together with <code>Judge</code>.</p>
<p>Since data from surveys and questionnaires are often coded (here, answer <em>#6</em> to question <code>Q10</code> means <em>Student</em>, while answer <em>#7</em> to the same question means <em>Qualified worker</em>), they first need to be decoded. In our case, the key to decode the data is stored in <code>demo_lev</code>.</p>
<p>Different strategies to decode the data are possible. One straight-forward strategy consists in automatically decoding each variable using <code>mutate()</code> and <code>factor()</code>. Another approach is considered here: Let’s start with building a long thin tibble with <code>pivot_longer()</code> that we merge to <code>demo_lev</code> by <code>Question</code> and <code>Response</code> using <code>inner_join()</code>. We prefer this solution here as it is simpler, faster, and independent of the number of variables to decode.</p>
<p>Once done, we can aggregate the results by <code>Question</code> and <code>Levels</code> (since we want to use the level information, not their code) and compute the frequency (<code>n()</code>) and the proportion (<code>N/sum(N)</code>)<a href="#fn45" class="footnote-ref" id="fnref45"><sup>45</sup></a>.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="data-analysis.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb358-2"><a href="data-analysis.html#cb358-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb358-3"><a href="data-analysis.html#cb358-3" aria-hidden="true" tabindex="-1"></a>demog_reduced <span class="ot">&lt;-</span> demographic <span class="sc">%&gt;%</span></span>
<span id="cb358-4"><a href="data-analysis.html#cb358-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, <span class="st">`</span><span class="at">Living area</span><span class="st">`</span>, Housing, <span class="st">`</span><span class="at">Income range</span><span class="st">`</span>, <span class="st">`</span><span class="at">Occupation</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb358-5"><a href="data-analysis.html#cb358-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>Judge, <span class="at">names_to =</span> <span class="st">&quot;Question&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Response&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb358-6"><a href="data-analysis.html#cb358-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(demo_lev, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;Question&quot;</span> <span class="ot">=</span> <span class="st">&quot;Name&quot;</span>, <span class="st">&quot;Response&quot;</span> <span class="ot">=</span> <span class="st">&quot;Code&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb358-7"><a href="data-analysis.html#cb358-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Question, Levels) <span class="sc">%&gt;%</span></span>
<span id="cb358-8"><a href="data-analysis.html#cb358-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb358-9"><a href="data-analysis.html#cb358-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Pct =</span> <span class="fu">percent</span>(N <span class="sc">/</span> <span class="fu">sum</span>(N), <span class="at">digits =</span> 1L)) <span class="sc">%&gt;%</span></span>
<span id="cb358-10"><a href="data-analysis.html#cb358-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<p>Histograms are a nice way to visualize proportions and to compare them over several variables. Such histograms can be obtained by splitting <code>demog_reduced</code> by <code>Question</code> and by creating them using either <code>N</code> or <code>Pct</code> (we are using <code>Pct</code> here). For simplicity, let’s order the levels decreasingly (<code>reorder</code>) and let’s represent them horizontally (<code>coord_flip()</code>). Of course, such graphs are automated across all questions using <code>map()</code>:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="data-analysis.html#cb359-1" aria-hidden="true" tabindex="-1"></a>demog_reduced <span class="sc">%&gt;%</span></span>
<span id="cb359-2"><a href="data-analysis.html#cb359-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">split</span>(.<span class="sc">$</span>Question) <span class="sc">%&gt;%</span></span>
<span id="cb359-3"><a href="data-analysis.html#cb359-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="cf">function</span>(data) {</span>
<span id="cb359-4"><a href="data-analysis.html#cb359-4" aria-hidden="true" tabindex="-1"></a>    var <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb359-5"><a href="data-analysis.html#cb359-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(Question) <span class="sc">%&gt;%</span></span>
<span id="cb359-6"><a href="data-analysis.html#cb359-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">unique</span>()</span>
<span id="cb359-7"><a href="data-analysis.html#cb359-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb359-8"><a href="data-analysis.html#cb359-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Levels, Pct), <span class="at">y =</span> Pct, <span class="at">label =</span> Pct)) <span class="sc">+</span></span>
<span id="cb359-9"><a href="data-analysis.html#cb359-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey50&quot;</span>) <span class="sc">+</span></span>
<span id="cb359-10"><a href="data-analysis.html#cb359-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> Pct <span class="sc">/</span> <span class="dv">2</span>), <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb359-11"><a href="data-analysis.html#cb359-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb359-12"><a href="data-analysis.html#cb359-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb359-13"><a href="data-analysis.html#cb359-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggtitle</span>(var) <span class="sc">+</span></span>
<span id="cb359-14"><a href="data-analysis.html#cb359-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb359-15"><a href="data-analysis.html#cb359-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">coord_flip</span>()</span>
<span id="cb359-16"><a href="data-analysis.html#cb359-16" aria-hidden="true" tabindex="-1"></a>  })</span></code></pre></div>
<pre><code>## $Housing</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-252-1.png" width="672" /></p>
<pre><code>## 
## $`Income range`</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-252-2.png" width="672" /></p>
<pre><code>## 
## $`Living area`</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-252-3.png" width="672" /></p>
<pre><code>## 
## $Occupation</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-252-4.png" width="672" /></p>
</div>
<div id="eating-behavior-traits-tfeq-data" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> Eating behavior traits: TFEQ data<a href="data-analysis.html#eating-behavior-traits-tfeq-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the same data set, consumers also answered some questions that reflect their relation to food <span class="citation">(<a href="#ref-stunkard1985" role="doc-biblioref">Stunkard and Messick 1985</a>)</span>. These questions can be categorized into three groups (also known as factors):</p>
<ul>
<li>Disinhibition (variables starting with <code>D</code>);</li>
<li>Restriction (variables starting with <code>R</code>);</li>
<li>Sensitivity to Hunger (variables starting with <code>H</code>).</li>
</ul>
<p>In order to analyze these three factors separately, we first need to select the corresponding variables. As we have seen earlier, such selection could be done by combining <code>dplyr::select()</code> to <code>starts_with("D")</code>, <code>starts_with("R")</code>, and/or <code>starts_with("H")</code>. However, this solution is not satisfactory as it also selects other variables that would start with any of these letters (e.g. Housing).</p>
<p>Instead, let’s take advantage of the fact that variable names have a recurring pattern (they all start with the letters D, R, or H, followed by a number) to introduce the notion of <em>regular expressions</em>.</p>
<p>Regular expressions are coded expression that allows finding patterns in names. In practice, generating a regular expression can be quite complex as it is an abstract concept which follows very specific rules. Fortunately, the package <code>{RVerbalExpression}</code> is a great assistant as it generates the regular expression for you thanks to understandable functions.
To create a regular expression using <code>{RVerbalExpression}</code>, we should first initiate it by calling the function <code>rx()</code> to which any relevant rules can be added. In our case, the variables must start with any of the letter R, D, or H, followed by a number (or more, as values go from 1 to 21). This can be done using the following code:</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="data-analysis.html#cb364-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RVerbalExpressions)</span>
<span id="cb364-2"><a href="data-analysis.html#cb364-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb364-3"><a href="data-analysis.html#cb364-3" aria-hidden="true" tabindex="-1"></a>rdh <span class="ot">&lt;-</span> <span class="fu">rx</span>() <span class="sc">%&gt;%</span></span>
<span id="cb364-4"><a href="data-analysis.html#cb364-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rx_either_of</span>(<span class="fu">c</span>(<span class="st">&quot;R&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;H&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb364-5"><a href="data-analysis.html#cb364-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rx_digit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb364-6"><a href="data-analysis.html#cb364-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rx_one_or_more</span>()</span></code></pre></div>
<p><code>rdh</code> is defined as (R|D|H) which corresponds to the regular expression we were looking for. We can then reduce (through <code>dplyr::select()</code>) the table to the variables that fit our regular expression by using the function <code>matches()</code>.</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="data-analysis.html#cb365-1" aria-hidden="true" tabindex="-1"></a>demographic <span class="sc">%&gt;%</span></span>
<span id="cb365-2"><a href="data-analysis.html#cb365-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">matches</span>(rdh))</span></code></pre></div>
<p>For each variable, let’s create a frequency table. Although we could use already build in functions, let’s customize our table (including raw frequency and percentages) as we want by creating our own function (called here <code>myfreq()</code>):</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="data-analysis.html#cb366-1" aria-hidden="true" tabindex="-1"></a>myfreq <span class="ot">&lt;-</span> <span class="cf">function</span>(data, info) {</span>
<span id="cb366-2"><a href="data-analysis.html#cb366-2" aria-hidden="true" tabindex="-1"></a>  var <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">unlist</span>(data<span class="sc">$</span>TFEQ))</span>
<span id="cb366-3"><a href="data-analysis.html#cb366-3" aria-hidden="true" tabindex="-1"></a>  info <span class="ot">&lt;-</span> info <span class="sc">%&gt;%</span></span>
<span id="cb366-4"><a href="data-analysis.html#cb366-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Name <span class="sc">==</span> var)</span>
<span id="cb366-5"><a href="data-analysis.html#cb366-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb366-6"><a href="data-analysis.html#cb366-6" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb366-7"><a href="data-analysis.html#cb366-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Response =</span> <span class="fu">factor</span>(Response, <span class="at">levels =</span> info<span class="sc">$</span>Code, <span class="at">labels =</span> info<span class="sc">$</span>Levels)) <span class="sc">%&gt;%</span></span>
<span id="cb366-8"><a href="data-analysis.html#cb366-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(Response) <span class="sc">%&gt;%</span></span>
<span id="cb366-9"><a href="data-analysis.html#cb366-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Response) <span class="sc">%&gt;%</span></span>
<span id="cb366-10"><a href="data-analysis.html#cb366-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb366-11"><a href="data-analysis.html#cb366-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Pct =</span> <span class="fu">percent</span>(N <span class="sc">/</span> <span class="fu">sum</span>(N), <span class="at">digits =</span> 1L)) <span class="sc">%&gt;%</span></span>
<span id="cb366-12"><a href="data-analysis.html#cb366-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb366-13"><a href="data-analysis.html#cb366-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb366-14"><a href="data-analysis.html#cb366-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(res)</span>
<span id="cb366-15"><a href="data-analysis.html#cb366-15" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>We then apply this function to each variable separately using <code>map()</code> after pivoting all these variables of interest (<code>pivot_longer()</code>) and splitting the data by <code>TFEQ</code> question:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="data-analysis.html#cb367-1" aria-hidden="true" tabindex="-1"></a>TFEQ_freq <span class="ot">&lt;-</span> demographic <span class="sc">%&gt;%</span></span>
<span id="cb367-2"><a href="data-analysis.html#cb367-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, <span class="fu">matches</span>(rdh)) <span class="sc">%&gt;%</span></span>
<span id="cb367-3"><a href="data-analysis.html#cb367-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>Judge, <span class="at">names_to =</span> <span class="st">&quot;TFEQ&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Response&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb367-4"><a href="data-analysis.html#cb367-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">split</span>(.<span class="sc">$</span>TFEQ) <span class="sc">%&gt;%</span></span>
<span id="cb367-5"><a href="data-analysis.html#cb367-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(myfreq, <span class="at">info =</span> demo_lev) <span class="sc">%&gt;%</span></span>
<span id="cb367-6"><a href="data-analysis.html#cb367-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">enframe</span>(<span class="at">name =</span> <span class="st">&quot;TFEQ&quot;</span>, <span class="at">value =</span> <span class="st">&quot;res&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb367-7"><a href="data-analysis.html#cb367-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(res) <span class="sc">%&gt;%</span></span>
<span id="cb367-8"><a href="data-analysis.html#cb367-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TFEQ =</span> <span class="fu">factor</span>(TFEQ, <span class="at">levels =</span> <span class="fu">unique</span>(<span class="fu">str_sort</span>(.<span class="sc">$</span>TFEQ, <span class="at">numeric =</span> <span class="cn">TRUE</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb367-9"><a href="data-analysis.html#cb367-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(TFEQ)</span></code></pre></div>
<p>From this table, histograms representing the frequency distribution for each variable can be created. But let’s suppose that we only want to display variables related to Disinhibition. To do so, we first need to generate the corresponding regular expression (only selecting variables starting with “D”) to filter the results before creating the plots:</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="data-analysis.html#cb368-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">rx</span>() <span class="sc">%&gt;%</span></span>
<span id="cb368-2"><a href="data-analysis.html#cb368-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rx_find</span>(<span class="st">&quot;D&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb368-3"><a href="data-analysis.html#cb368-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rx_digit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb368-4"><a href="data-analysis.html#cb368-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rx_one_or_more</span>()</span>
<span id="cb368-5"><a href="data-analysis.html#cb368-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb368-6"><a href="data-analysis.html#cb368-6" aria-hidden="true" tabindex="-1"></a>TFEQ_freq <span class="sc">%&gt;%</span></span>
<span id="cb368-7"><a href="data-analysis.html#cb368-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(TFEQ, d)) <span class="sc">%&gt;%</span></span>
<span id="cb368-8"><a href="data-analysis.html#cb368-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Response, <span class="at">y =</span> Pct, <span class="at">label =</span> Pct)) <span class="sc">+</span></span>
<span id="cb368-9"><a href="data-analysis.html#cb368-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;grey50&quot;</span>) <span class="sc">+</span></span>
<span id="cb368-10"><a href="data-analysis.html#cb368-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y =</span> Pct <span class="sc">/</span> <span class="dv">2</span>), <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb368-11"><a href="data-analysis.html#cb368-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb368-12"><a href="data-analysis.html#cb368-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">angle =</span> <span class="dv">30</span>)) <span class="sc">+</span></span>
<span id="cb368-13"><a href="data-analysis.html#cb368-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>TFEQ, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-257-1.png" width="672" /></p>
<p>Structured questionnaires such as the TFEQ are very frequent in sensory and consumer science. They are used to measure individual patterns as diverse as personality traits, attitudes, food choice motives, engagement, social desirability bias, etc. Ultimately, the TFEQ questionnaire consists in a set of structured questions whose respective answers combine to provide a TFEQ score (actually, three scores, one for Disinhibition, one for Restriction and one for sensitivity to Hunger). This TFEQ scores translate into certain food behavior tendencies.</p>
<p>However, computing the TFEQ scores is slightly more complicated than adding the scores of all TFEQ questions together. Instead, they follow certain rules that are stored in the <em>Variables</em> sheet in <em>biscuits_traits.xlsx</em>. For each TFEQ question, the rule to follow is provided by <code>Direction</code> and <code>Value</code>, and works as following: if the condition provided by <code>Direction</code> and <code>Value</code> is met, then the respondent gets a 1, else a 0. Ultimately, the TFEQ score is the sum of all these evaluations.</p>
<p>Let’s start by extracting this information (<code>Direction</code> and <code>Value</code>) from the <em>Variables</em> sheet for all the variables involved in the computation of the TFEQ scores. We store this in <code>var_drh</code>.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="data-analysis.html#cb369-1" aria-hidden="true" tabindex="-1"></a>var_rdh <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Variables&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb369-2"><a href="data-analysis.html#cb369-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(Name, rdh)) <span class="sc">%&gt;%</span></span>
<span id="cb369-3"><a href="data-analysis.html#cb369-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Name, Direction, Value)</span></code></pre></div>
<p>This information is added to <code>demographic</code>.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="data-analysis.html#cb370-1" aria-hidden="true" tabindex="-1"></a>TFEQ <span class="ot">&lt;-</span> demographic <span class="sc">%&gt;%</span></span>
<span id="cb370-2"><a href="data-analysis.html#cb370-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, <span class="fu">matches</span>(rdh)) <span class="sc">%&gt;%</span></span>
<span id="cb370-3"><a href="data-analysis.html#cb370-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>Judge, <span class="at">names_to =</span> <span class="st">&quot;DHR&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Score&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb370-4"><a href="data-analysis.html#cb370-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(var_rdh, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;DHR&quot;</span> <span class="ot">=</span> <span class="st">&quot;Name&quot;</span>))</span></code></pre></div>
<p>Since we need to evaluate each assessors’ answer to the TFEQ questions, we create a new variable <code>TFEQValue</code> which takes a 1 if the corresponding condition is met, and a 0 otherwise. Such approach is done through <code>mutate()</code> combined with a succession of intertwined <code>ifelse()</code> functions.<a href="#fn46" class="footnote-ref" id="fnref46"><sup>46</sup></a></p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="data-analysis.html#cb371-1" aria-hidden="true" tabindex="-1"></a>TFEQ_coded <span class="ot">&lt;-</span> TFEQ <span class="sc">%&gt;%</span></span>
<span id="cb371-2"><a href="data-analysis.html#cb371-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TFEQValue =</span> <span class="fu">ifelse</span>(Direction <span class="sc">==</span> <span class="st">&quot;Equal&quot;</span> <span class="sc">&amp;</span> Score <span class="sc">==</span> Value, <span class="dv">1</span>,</span>
<span id="cb371-3"><a href="data-analysis.html#cb371-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Direction <span class="sc">==</span> <span class="st">&quot;Superior&quot;</span> <span class="sc">&amp;</span> Score <span class="sc">&gt;</span> Value, <span class="dv">1</span>,</span>
<span id="cb371-4"><a href="data-analysis.html#cb371-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ifelse</span>(Direction <span class="sc">==</span> <span class="st">&quot;Inferior&quot;</span> <span class="sc">&amp;</span> Score <span class="sc">&lt;</span> Value, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb371-5"><a href="data-analysis.html#cb371-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb371-6"><a href="data-analysis.html#cb371-6" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb371-7"><a href="data-analysis.html#cb371-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Factor =</span> <span class="fu">ifelse</span>(<span class="fu">str_starts</span>(.<span class="sc">$</span>DHR, <span class="st">&quot;D&quot;</span>), <span class="st">&quot;Disinhibition&quot;</span>,</span>
<span id="cb371-8"><a href="data-analysis.html#cb371-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(<span class="fu">str_starts</span>(.<span class="sc">$</span>DHR, <span class="st">&quot;H&quot;</span>), <span class="st">&quot;Hunger&quot;</span>, <span class="st">&quot;Restriction&quot;</span>)</span>
<span id="cb371-9"><a href="data-analysis.html#cb371-9" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb371-10"><a href="data-analysis.html#cb371-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Factor =</span> <span class="fu">factor</span>(Factor, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Restriction&quot;</span>, <span class="st">&quot;Disinhibition&quot;</span>, <span class="st">&quot;Hunger&quot;</span>)))</span></code></pre></div>
<p>Ultimately, we compute the TFEQ Score by summing across all <code>TFEQValue</code> per respondent, by maintaining the distinction between each category. Note that the final score is stored in <code>Total</code>, which corresponds to sum across categories:</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="data-analysis.html#cb372-1" aria-hidden="true" tabindex="-1"></a>TFEQ_score <span class="ot">&lt;-</span> TFEQ_coded <span class="sc">%&gt;%</span></span>
<span id="cb372-2"><a href="data-analysis.html#cb372-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Judge, Factor) <span class="sc">%&gt;%</span></span>
<span id="cb372-3"><a href="data-analysis.html#cb372-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">TFEQ =</span> <span class="fu">sum</span>(TFEQValue)) <span class="sc">%&gt;%</span></span>
<span id="cb372-4"><a href="data-analysis.html#cb372-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Judge =</span> <span class="fu">factor</span>(Judge, <span class="at">levels =</span> <span class="fu">unique</span>(<span class="fu">str_sort</span>(.<span class="sc">$</span>Judge, <span class="at">numeric =</span> <span class="cn">TRUE</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb372-5"><a href="data-analysis.html#cb372-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Judge) <span class="sc">%&gt;%</span></span>
<span id="cb372-6"><a href="data-analysis.html#cb372-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Factor, <span class="at">values_from =</span> TFEQ) <span class="sc">%&gt;%</span></span>
<span id="cb372-7"><a href="data-analysis.html#cb372-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Total =</span> <span class="fu">sum</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric))))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Judge&#39;. You can
## override using the `.groups` argument.</code></pre>
<p>Such results can then be visualized graphically, for instance by representing the distribution of <code>TFEQ_score</code> for the 3 TFEQ factors:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="data-analysis.html#cb374-1" aria-hidden="true" tabindex="-1"></a>TFEQ_score <span class="sc">%&gt;%</span></span>
<span id="cb374-2"><a href="data-analysis.html#cb374-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Total) <span class="sc">%&gt;%</span></span>
<span id="cb374-3"><a href="data-analysis.html#cb374-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>Judge, <span class="at">names_to =</span> <span class="st">&quot;Factor&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Scores&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb374-4"><a href="data-analysis.html#cb374-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Scores, <span class="at">color =</span> Factor)) <span class="sc">+</span></span>
<span id="cb374-5"><a href="data-analysis.html#cb374-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">key_glyph =</span> <span class="st">&quot;path&quot;</span>) <span class="sc">+</span></span>
<span id="cb374-6"><a href="data-analysis.html#cb374-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;TFEQ Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb374-7"><a href="data-analysis.html#cb374-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb374-8"><a href="data-analysis.html#cb374-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">linetype =</span> <span class="dv">1</span>))) <span class="sc">+</span></span>
<span id="cb374-9"><a href="data-analysis.html#cb374-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Distribution of the Individual TFEQ-factor Scores&quot;</span>) <span class="sc">+</span></span>
<span id="cb374-10"><a href="data-analysis.html#cb374-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-262-1.png" width="672" /></p>
</div>
</div>
<div id="tibble-use" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Consumer Data<a href="data-analysis.html#tibble-use" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The analysis of consumer data usually involves the same type of analysis as the ones for sensory data (e.g. ANOVA, PCA, etc.), but the way the data is being collected (absence of duplicates) and its underlying nature (affect vs. descriptive) require some adjustments.</p>
<p>Let’s start by importing the consumer data that is stored in <em>biscuits_consumer_test.xlsx</em>. Here, we import two sheets, one with the consumption time and number of biscuits (stored in <code>Nbiscuit</code>), and one with different consumer evaluations of the samples (stored in <code>consumer</code>)</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="data-analysis.html#cb375-1" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">&quot;Data&quot;</span>, <span class="st">&quot;biscuits_consumer_test.xlsx&quot;</span>)</span>
<span id="cb375-2"><a href="data-analysis.html#cb375-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb375-3"><a href="data-analysis.html#cb375-3" aria-hidden="true" tabindex="-1"></a>Nbiscuit <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Time Consumption&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb375-4"><a href="data-analysis.html#cb375-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Product =</span> <span class="fu">str_c</span>(<span class="st">&quot;P&quot;</span>, Product)) <span class="sc">%&gt;%</span></span>
<span id="cb375-5"><a href="data-analysis.html#cb375-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">N =</span> <span class="st">`</span><span class="at">Nb biscuits</span><span class="st">`</span>)</span>
<span id="cb375-6"><a href="data-analysis.html#cb375-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb375-7"><a href="data-analysis.html#cb375-7" aria-hidden="true" tabindex="-1"></a>consumer <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(file_path, <span class="at">sheet =</span> <span class="st">&quot;Biscuits&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb375-8"><a href="data-analysis.html#cb375-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Judge =</span> Consumer, <span class="at">Product =</span> Samples) <span class="sc">%&gt;%</span></span>
<span id="cb375-9"><a href="data-analysis.html#cb375-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Judge =</span> <span class="fu">str_c</span>(<span class="st">&quot;J&quot;</span>, Judge), <span class="at">Product =</span> <span class="fu">str_c</span>(<span class="st">&quot;P&quot;</span>, Product)) <span class="sc">%&gt;%</span></span>
<span id="cb375-10"><a href="data-analysis.html#cb375-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(Nbiscuit, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;Judge&quot;</span>, <span class="st">&quot;Product&quot;</span>))</span></code></pre></div>
<p>Similarly to the sensory data, let’s start with computing the mean liking score per product after the first bite (<code>1stbite_liking</code>) and at the end of the evaluation (<code>after_liking</code>).</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="data-analysis.html#cb376-1" aria-hidden="true" tabindex="-1"></a>consumer <span class="sc">%&gt;%</span></span>
<span id="cb376-2"><a href="data-analysis.html#cb376-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, Product, <span class="st">`</span><span class="at">1stbite_liking</span><span class="st">`</span>, <span class="st">`</span><span class="at">after_liking</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb376-3"><a href="data-analysis.html#cb376-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Product) <span class="sc">%&gt;%</span></span>
<span id="cb376-4"><a href="data-analysis.html#cb376-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), mean))</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    Product `1stbite_liking` after_liking
##    &lt;chr&gt;              &lt;dbl&gt;        &lt;dbl&gt;
##  1 P1                  6.30         6.26
##  2 P10                 7.40         7.57
##  3 P2                  5.53         5.38
##  4 P3                  3.94         3.49
##  5 P4                  3.00         2.72
##  6 P5                  5.78         5.73
##  7 P6                  4.25         4.19
##  8 P7                  4.87         4.71
##  9 P8                  2.99         2.83
## 10 P9                  3.51         3.18</code></pre>
<p>A first glance at the table shows that there are clear differences between the samples (within a liking variable), but little difference between liking variables (within a sample).</p>
<p>Of course, we want to know if differences between samples are significant. We thus need to perform an 2-way ANOVA (testing for the product effect by also taking into account the individual differences) followed up by a paired comparison test (here Tukey’s HSD). For the latter, the <code>{agricolae}</code> package is a good solution, as it is simple to use and has all its built-in tests working in the same way.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="data-analysis.html#cb378-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb378-2"><a href="data-analysis.html#cb378-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb378-3"><a href="data-analysis.html#cb378-3" aria-hidden="true" tabindex="-1"></a>liking_start <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">1stbite_liking</span><span class="st">`</span> <span class="sc">~</span> Product <span class="sc">+</span> Judge, <span class="at">data =</span> consumer)</span>
<span id="cb378-4"><a href="data-analysis.html#cb378-4" aria-hidden="true" tabindex="-1"></a>liking_start_hsd <span class="ot">&lt;-</span> <span class="fu">HSD.test</span>(liking_start, <span class="st">&quot;Product&quot;</span>)<span class="sc">$</span>groups <span class="sc">%&gt;%</span></span>
<span id="cb378-5"><a href="data-analysis.html#cb378-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb378-6"><a href="data-analysis.html#cb378-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb378-7"><a href="data-analysis.html#cb378-7" aria-hidden="true" tabindex="-1"></a>liking_start_hsd</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    Product `1stbite_liking` groups
##    &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt; 
##  1 P10                 7.40 a     
##  2 P1                  6.30 b     
##  3 P5                  5.78 b     
##  4 P2                  5.53 bc    
##  5 P7                  4.87 cd    
##  6 P6                  4.25 de    
##  7 P3                  3.94 e     
##  8 P9                  3.51 ef    
##  9 P4                  3.00 f     
## 10 P8                  2.99 f</code></pre>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="data-analysis.html#cb380-1" aria-hidden="true" tabindex="-1"></a>liking_end <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">after_liking</span><span class="st">`</span> <span class="sc">~</span> Product <span class="sc">+</span> Judge, <span class="at">data =</span> consumer)</span>
<span id="cb380-2"><a href="data-analysis.html#cb380-2" aria-hidden="true" tabindex="-1"></a>liking_end_hsd <span class="ot">&lt;-</span> <span class="fu">HSD.test</span>(liking_end, <span class="st">&quot;Product&quot;</span>)<span class="sc">$</span>groups <span class="sc">%&gt;%</span></span>
<span id="cb380-3"><a href="data-analysis.html#cb380-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Product&quot;</span>)</span></code></pre></div>
<p>Both at the start and at the end of the evaluation, significant differences (at 5%) in liking between samples are observed according to Tukey’s HSD test.</p>
<p>To further compare the liking assessment of the samples after the first bite and at the end of the tasting, the results obtained from <code>liking_start_hsd</code> and <code>liking_end_hsd</code> are combined. We then represent the results in a bar-chart:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="data-analysis.html#cb381-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(</span>
<span id="cb381-2"><a href="data-analysis.html#cb381-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Start =</span> liking_start_hsd <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Liking =</span> <span class="st">`</span><span class="at">1stbite_liking</span><span class="st">`</span>),</span>
<span id="cb381-3"><a href="data-analysis.html#cb381-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">End =</span> liking_end_hsd <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Liking =</span> <span class="st">`</span><span class="at">after_liking</span><span class="st">`</span>)</span>
<span id="cb381-4"><a href="data-analysis.html#cb381-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb381-5"><a href="data-analysis.html#cb381-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">enframe</span>(<span class="at">name =</span> <span class="st">&quot;Moment&quot;</span>, <span class="at">value =</span> <span class="st">&quot;res&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb381-6"><a href="data-analysis.html#cb381-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(res) <span class="sc">%&gt;%</span></span>
<span id="cb381-7"><a href="data-analysis.html#cb381-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Moment =</span> <span class="fu">factor</span>(Moment, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Start&quot;</span>, <span class="st">&quot;End&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb381-8"><a href="data-analysis.html#cb381-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Product, <span class="sc">-</span>Liking), <span class="at">y =</span> Liking, <span class="at">fill =</span> Moment)) <span class="sc">+</span></span>
<span id="cb381-9"><a href="data-analysis.html#cb381-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span></span>
<span id="cb381-10"><a href="data-analysis.html#cb381-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb381-11"><a href="data-analysis.html#cb381-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Comparison of the liking scores at the start and at the end of the evaluation&quot;</span>) <span class="sc">+</span></span>
<span id="cb381-12"><a href="data-analysis.html#cb381-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-266-1.png" width="672" /></p>
<p>As can be seen, the pattern of liking scores across samples is indeed very stable across the evaluation, particularly in terms of rank. At the individual level, such linear relationship is also observed (here for the first 12 consumers):</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="data-analysis.html#cb382-1" aria-hidden="true" tabindex="-1"></a>consumer <span class="sc">%&gt;%</span></span>
<span id="cb382-2"><a href="data-analysis.html#cb382-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, Product, <span class="at">Start =</span> <span class="st">`</span><span class="at">1stbite_liking</span><span class="st">`</span>, <span class="at">End =</span> <span class="st">`</span><span class="at">after_liking</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb382-3"><a href="data-analysis.html#cb382-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Judge <span class="sc">%in%</span> <span class="fu">str_c</span>(<span class="st">&quot;J&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb382-4"><a href="data-analysis.html#cb382-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Judge =</span> <span class="fu">factor</span>(Judge, <span class="at">levels =</span> <span class="fu">unique</span>(<span class="fu">str_sort</span>(.<span class="sc">$</span>Judge, <span class="at">numeric =</span> <span class="cn">TRUE</span>)))) <span class="sc">%&gt;%</span></span>
<span id="cb382-5"><a href="data-analysis.html#cb382-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Start, <span class="at">y =</span> End)) <span class="sc">+</span></span>
<span id="cb382-6"><a href="data-analysis.html#cb382-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb382-7"><a href="data-analysis.html#cb382-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> <span class="st">&quot;y~x&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb382-8"><a href="data-analysis.html#cb382-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb382-9"><a href="data-analysis.html#cb382-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Overall Liking&quot;</span>, <span class="st">&quot;(Assessment after first bite vs. end of the tasting)&quot;</span>) <span class="sc">+</span></span>
<span id="cb382-10"><a href="data-analysis.html#cb382-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Judge)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-267-1.png" width="672" /></p>
<blockquote>
<p>For your own curiosity, we invite you to re-create the same graph by comparing the Liking score at the end of the evaluation (<code>after_liking</code>) with the liking score measured on the 9pt categorical scale (<code>end_liking 9pt</code>), and to reflect on the results obtained. Are the consumers consistent in their evaluations?</p>
</blockquote>
<p>Another interesting relationship to study involves the liking scores<a href="#fn47" class="footnote-ref" id="fnref47"><sup>47</sup></a> and the number of cookies eaten by each consumer. We could follow the same procedure as before, but prefer to add here a filter to only show consumers with a significant regression line at 5%.</p>
<p>Let’s start by creating a function called <code>run_reg()</code> that runs the regression analysis of the number of biscuits (<code>N</code>) in function of the liking score (<code>Liking</code>):</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="data-analysis.html#cb383-1" aria-hidden="true" tabindex="-1"></a>run_reg <span class="ot">&lt;-</span> <span class="cf">function</span>(df) {</span>
<span id="cb383-2"><a href="data-analysis.html#cb383-2" aria-hidden="true" tabindex="-1"></a>  output <span class="ot">&lt;-</span> <span class="fu">lm</span>(N <span class="sc">~</span> Liking, <span class="at">data =</span> df)</span>
<span id="cb383-3"><a href="data-analysis.html#cb383-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(output)</span>
<span id="cb383-4"><a href="data-analysis.html#cb383-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>After transforming the data, we apply this function to each consumer separately.</p>
<p>Here, we take advantage of the flexibility of tibbles as it allows storing results as list by saving three sorts of outputs per consumer:</p>
<ul>
<li><code>data</code> contains the individual data;</li>
<li><code>lm_obj</code> corresponds to the results of the linear model (obtained with `run_reg()``);</li>
<li><code>glance</code> contains some general results of the model incl. R2, the p-value, etc.</li>
</ul>
<blockquote>
<p>These three outputs contain completely different information for the same analysis (here regressions). The fact that tibbles allow storing outputs as list is very handy since all the results are tidied in one unique R object, which can then easily be accessed by unfolding the output needed.</p>
</blockquote>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="data-analysis.html#cb384-1" aria-hidden="true" tabindex="-1"></a>N_liking_reg <span class="ot">&lt;-</span> consumer <span class="sc">%&gt;%</span></span>
<span id="cb384-2"><a href="data-analysis.html#cb384-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, Product, <span class="at">Liking =</span> <span class="st">`</span><span class="at">end_liking 9pt</span><span class="st">`</span>, N) <span class="sc">%&gt;%</span></span>
<span id="cb384-3"><a href="data-analysis.html#cb384-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Liking =</span> <span class="dv">10</span> <span class="sc">-</span> Liking) <span class="sc">%&gt;%</span></span>
<span id="cb384-4"><a href="data-analysis.html#cb384-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Judge) <span class="sc">%&gt;%</span></span>
<span id="cb384-5"><a href="data-analysis.html#cb384-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb384-6"><a href="data-analysis.html#cb384-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb384-7"><a href="data-analysis.html#cb384-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lm_obj =</span> <span class="fu">map</span>(data, run_reg)) <span class="sc">%&gt;%</span></span>
<span id="cb384-8"><a href="data-analysis.html#cb384-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">glance =</span> <span class="fu">map</span>(lm_obj, broom<span class="sc">::</span>glance))</span></code></pre></div>
<p>Since we only want to represent consumers with a significant regression line, we unfold the results stored in <code>glance</code> so that we can access the <code>p.value</code> of each regression.</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="data-analysis.html#cb385-1" aria-hidden="true" tabindex="-1"></a>N_liking <span class="ot">&lt;-</span> N_liking_reg <span class="sc">%&gt;%</span></span>
<span id="cb385-2"><a href="data-analysis.html#cb385-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(glance) <span class="sc">%&gt;%</span></span>
<span id="cb385-3"><a href="data-analysis.html#cb385-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p.value <span class="sc">&lt;=</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span></span>
<span id="cb385-4"><a href="data-analysis.html#cb385-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(p.value) <span class="sc">%&gt;%</span></span>
<span id="cb385-5"><a href="data-analysis.html#cb385-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Judge =</span> <span class="fu">fct_reorder</span>(Judge, p.value)) <span class="sc">%&gt;%</span></span>
<span id="cb385-6"><a href="data-analysis.html#cb385-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data)</span></code></pre></div>
<p>Ultimately, the relationship between the liking score and the number of biscuits eaten is represented in a line chart:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="data-analysis.html#cb386-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(N_liking, <span class="fu">aes</span>(<span class="at">x =</span> Liking, <span class="at">y =</span> N)) <span class="sc">+</span></span>
<span id="cb386-2"><a href="data-analysis.html#cb386-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb386-3"><a href="data-analysis.html#cb386-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> <span class="st">&quot;y~x&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb386-4"><a href="data-analysis.html#cb386-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb386-5"><a href="data-analysis.html#cb386-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Number of Biscuits vs. Liking&quot;</span>, <span class="st">&quot;(Consumers with a significant (5%) regression model are shown (ordered from the most to the least signif.)&quot;</span>) <span class="sc">+</span></span>
<span id="cb386-6"><a href="data-analysis.html#cb386-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Judge, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-271-1.png" width="672" /></p>
</div>
<div id="combining-sensory-and-consumer-data" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Combining Sensory and Consumer Data<a href="data-analysis.html#combining-sensory-and-consumer-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="internal-preference-mapping" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Internal Preference Mapping<a href="data-analysis.html#internal-preference-mapping" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we’ve analyzed the sensory and the consumer data separately, it is time to combine both data sets and analyze them conjointly. A first analysis that can then be performed is the internal preference mapping, i.e. a PCA on the consumer liking scores in which the sensory attributes are projected as supplementary.</p>
<p>Such analysis is split in 3 steps:</p>
<ol style="list-style-type: decimal">
<li>The consumer data is re-organized in a wide format with the samples in rows and the consumers in columns;</li>
<li>The sensory mean table is joined to the consumer data (make sure that the product names perfectly match in the two files);</li>
<li>A PCA is performed on the consumer data, the sensory descriptors being projected as supplementary variables.</li>
</ol>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="data-analysis.html#cb387-1" aria-hidden="true" tabindex="-1"></a>consumer_wide <span class="ot">&lt;-</span> consumer <span class="sc">%&gt;%</span></span>
<span id="cb387-2"><a href="data-analysis.html#cb387-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Product, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;P&quot;</span>, <span class="st">&quot;Number&quot;</span>), <span class="at">sep =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb387-3"><a href="data-analysis.html#cb387-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Number =</span> <span class="fu">ifelse</span>(<span class="fu">nchar</span>(Number) <span class="sc">==</span> <span class="dv">1</span>, <span class="fu">str_c</span>(<span class="st">&quot;0&quot;</span>, Number), Number)) <span class="sc">%&gt;%</span></span>
<span id="cb387-4"><a href="data-analysis.html#cb387-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(Product, P, Number, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb387-5"><a href="data-analysis.html#cb387-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, Product, <span class="at">Liking =</span> <span class="st">`</span><span class="at">end_liking 9pt</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb387-6"><a href="data-analysis.html#cb387-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Liking =</span> <span class="dv">10</span> <span class="sc">-</span> Liking) <span class="sc">%&gt;%</span></span>
<span id="cb387-7"><a href="data-analysis.html#cb387-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Judge, <span class="at">values_from =</span> Liking)</span>
<span id="cb387-8"><a href="data-analysis.html#cb387-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb387-9"><a href="data-analysis.html#cb387-9" aria-hidden="true" tabindex="-1"></a>data_mdpref <span class="ot">&lt;-</span> senso_mean <span class="sc">%&gt;%</span></span>
<span id="cb387-10"><a href="data-analysis.html#cb387-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(consumer_wide, <span class="at">by =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb387-11"><a href="data-analysis.html#cb387-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb387-12"><a href="data-analysis.html#cb387-12" aria-hidden="true" tabindex="-1"></a>res_mdpref <span class="ot">&lt;-</span> data_mdpref <span class="sc">%&gt;%</span></span>
<span id="cb387-13"><a href="data-analysis.html#cb387-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb387-14"><a href="data-analysis.html#cb387-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb387-15"><a href="data-analysis.html#cb387-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">PCA</span>(., <span class="at">quali.sup =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">quanti.sup =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">34</span>, <span class="at">graph =</span> <span class="cn">FALSE</span>)</span>
<span id="cb387-16"><a href="data-analysis.html#cb387-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb387-17"><a href="data-analysis.html#cb387-17" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(res_mdpref, <span class="at">habillage =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-272-1.png" width="672" /></p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="data-analysis.html#cb388-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(res_mdpref, <span class="at">label =</span> <span class="st">&quot;quanti.sup&quot;</span>, <span class="at">select.var =</span> <span class="fu">list</span>(<span class="at">cos2 =</span> <span class="fl">0.5</span>), <span class="at">repel =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: ggrepel: 3 unlabeled data points (too many
## overlaps). Consider increasing max.overlaps</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-272-2.png" width="672" /></p>
<p>As can be seen, the consumers are quite in agreement as all the black arrows are pointing in a similar direction.
In overall, they seem to like biscuits that are sweet, with cereal flavor, and fatty/dairy flavor and odor, and dislike biscuits defined as astringent, dry in mouth, uneven and with dark external color.</p>
</div>
<div id="hac" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Consumers Clustering<a href="data-analysis.html#hac" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Although the data show a fairly good agreement between consumers, let’s cluster them in more homogeneous groups based on liking.</p>
<p>Various solutions for clustering exist, depending on the type of distance (similarity or dissimilarity), the linkage (single, average, Ward, etc.), and of course the algorithm itself (e.g. AHC, k-means, etc.).</p>
<p>Here, we opt for the Agglomerative Hierarchical Clustering (AHC) with Euclidean distance (dissimilarity) and Ward criterion, as it is a fairly common approach in Sensory and Consumer research. Such analysis can be done using <code>stats::hclust()</code> or <code>cluster::agnes()</code>.</p>
<blockquote>
<p>Before computing the distance between consumers, it is advised to at least center their liking scores (subtracting their mean liking scores to each of their individual scores) as it allows grouping consumers based on their respective preferences, rather than on their scale usage (otherwise, consumers who scored high on all samples are grouped together, and separated from consumers who scored low on all samples, which isn’t so much informative). Such transformation can be done automatically using the <code>scale()</code><a href="#fn48" class="footnote-ref" id="fnref48"><sup>48</sup></a> function.</p>
</blockquote>
<p>Let’s start with computing the euclidean distance between each pair of consumers by using the <code>dist()</code> function.</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="data-analysis.html#cb390-1" aria-hidden="true" tabindex="-1"></a>consumer_dist <span class="ot">&lt;-</span> consumer_wide <span class="sc">%&gt;%</span></span>
<span id="cb390-2"><a href="data-analysis.html#cb390-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb390-3"><a href="data-analysis.html#cb390-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb390-4"><a href="data-analysis.html#cb390-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale</span>(., <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb390-5"><a href="data-analysis.html#cb390-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>(.) <span class="sc">%&gt;%</span></span>
<span id="cb390-6"><a href="data-analysis.html#cb390-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dist</span>(., <span class="at">method =</span> <span class="st">&quot;euclidean&quot;</span>)</span></code></pre></div>
<p>The AHC is performed using the <code>hclust()</code> function and the <code>method = "ward.D2"</code> parameter, which is the equivalent to <code>method = "ward"</code> for <code>agnes()</code>. To visualize the dendrogram, the <code>factoextra::fviz_dend()</code> function is used (here we propose to visualize the 2-clusters solution by setting <code>k=2</code>):</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="data-analysis.html#cb391-1" aria-hidden="true" tabindex="-1"></a>res_hclust <span class="ot">&lt;-</span> <span class="fu">hclust</span>(consumer_dist, <span class="at">method =</span> <span class="st">&quot;ward.D2&quot;</span>)</span>
<span id="cb391-2"><a href="data-analysis.html#cb391-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_dend</span>(res_hclust, <span class="at">k =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-274-1.png" width="672" /></p>
<blockquote>
<p>An interesting option to visualize clusters and proposed by <code>fviz_dend()</code> is the <em>phologenic</em> representation (<code>type="phylogenic"</code>). We invite you to give it a try to see how it represents the clusters as an alternative to the classical dendrogram tree.</p>
</blockquote>
<p>Since we are satisfied with the 2 clusters solution, we cut the tree (using <code>cutree()</code>) at this level using, hence generating a group of 74 and a group of 33 consumers.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="data-analysis.html#cb392-1" aria-hidden="true" tabindex="-1"></a>res_clust <span class="ot">&lt;-</span> <span class="fu">cutree</span>(res_hclust, <span class="at">k =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb392-2"><a href="data-analysis.html#cb392-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Judge&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb392-3"><a href="data-analysis.html#cb392-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Cluster =</span> value) <span class="sc">%&gt;%</span></span>
<span id="cb392-4"><a href="data-analysis.html#cb392-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Cluster =</span> <span class="fu">as.character</span>(Cluster))</span>
<span id="cb392-5"><a href="data-analysis.html#cb392-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb392-6"><a href="data-analysis.html#cb392-6" aria-hidden="true" tabindex="-1"></a>res_clust <span class="sc">%&gt;%</span></span>
<span id="cb392-7"><a href="data-analysis.html#cb392-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Cluster)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   Cluster     n
##   &lt;chr&gt;   &lt;int&gt;
## 1 1          74
## 2 2          33</code></pre>
<p>Lastly, we compare visually the preference patterns between clusters by representing in a line chart the average liking score for each product provided by each cluster.</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="data-analysis.html#cb394-1" aria-hidden="true" tabindex="-1"></a>mean_cluster <span class="ot">&lt;-</span> consumer <span class="sc">%&gt;%</span></span>
<span id="cb394-2"><a href="data-analysis.html#cb394-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Product, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;P&quot;</span>, <span class="st">&quot;Number&quot;</span>), <span class="at">sep =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb394-3"><a href="data-analysis.html#cb394-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Number =</span> <span class="fu">ifelse</span>(<span class="fu">nchar</span>(Number) <span class="sc">==</span> <span class="dv">1</span>, <span class="fu">str_c</span>(<span class="st">&quot;0&quot;</span>, Number), Number)) <span class="sc">%&gt;%</span></span>
<span id="cb394-4"><a href="data-analysis.html#cb394-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(Product, P, Number, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb394-5"><a href="data-analysis.html#cb394-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Judge, Product, <span class="at">Liking =</span> <span class="st">`</span><span class="at">end_liking 9pt</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb394-6"><a href="data-analysis.html#cb394-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Liking =</span> <span class="dv">10</span> <span class="sc">-</span> Liking) <span class="sc">%&gt;%</span></span>
<span id="cb394-7"><a href="data-analysis.html#cb394-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(res_clust, <span class="at">by =</span> <span class="st">&quot;Judge&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb394-8"><a href="data-analysis.html#cb394-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Product, Cluster) <span class="sc">%&gt;%</span></span>
<span id="cb394-9"><a href="data-analysis.html#cb394-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Liking =</span> <span class="fu">mean</span>(Liking), <span class="at">N =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb394-10"><a href="data-analysis.html#cb394-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Cluster =</span> <span class="fu">str_c</span>(Cluster, <span class="st">&quot; (&quot;</span>, N, <span class="st">&quot;)&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb394-11"><a href="data-analysis.html#cb394-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Product&#39;. You can
## override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="data-analysis.html#cb396-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_cluster, <span class="fu">aes</span>(<span class="at">x =</span> Product, <span class="at">y =</span> Liking, <span class="at">colour =</span> Cluster, <span class="at">group =</span> Cluster)) <span class="sc">+</span></span>
<span id="cb396-2"><a href="data-analysis.html#cb396-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">pch =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb396-3"><a href="data-analysis.html#cb396-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> Cluster), <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb396-4"><a href="data-analysis.html#cb396-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb396-5"><a href="data-analysis.html#cb396-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">&quot;Average Liking Score&quot;</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">9</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">9</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb396-6"><a href="data-analysis.html#cb396-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Cluster differences in the appreciation of the Products (using hclust)&quot;</span>) <span class="sc">+</span></span>
<span id="cb396-7"><a href="data-analysis.html#cb396-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-276-1.png" width="672" /></p>
<p>It appears that cluster 1 (74 consumers) particularly likes <code>P10</code>, <code>P01</code>, and <code>P05</code>, and has a fairly flat liking pattern otherwise. On the other hand, the cluster 2 (33 consumers) expressed strong rejections towards <code>P04</code> and <code>P08</code>, and like <code>P10</code> and <code>P01</code> the most.</p>
<p>The fact that both clusters agree on the best samples (<code>P10</code> and <code>P01</code>) goes with our original assumption from the Internal Preference Mapping that the panel of consumers is fairly homogeneous in terms of preferences.</p>
<blockquote>
<p>In <code>{FactoMineR}</code>, the <code>HCPC()</code> function also performs AHC but takes as starting point the results of a multivariate analysis (HCPC stands for Hierarchical Clustering on Principal Components). This would typically be the results of the PCA performed on the Consumer (rows) <em>x</em> Product (columns) matrix of liking scores, in which the scores are (at least) centered in row.
Although results should be identical in most cases, it can happen that results slightly diverge from <code>agnes()</code> and <code>hclust()</code> as it also depends on the number of dimensions kept in the multivariate analysis and on the treatment of in-between clusters consumers. But more interestingly, <code>HCPC()</code> offers the possibility to <em>consolidate</em> the clusters by performing k-means on the solution obtained from the AHC (<code>consol=TRUE</code>).</p>
</blockquote>
</div>
<div id="drivers-of-liking" class="section level3 hasAnchor" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Drivers of Liking<a href="data-analysis.html#drivers-of-liking" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When combining sensory and consumer data collected on the same product, it is also relevant to understand which sensory properties of the products drive the consumers’ liking and disliking. Such evaluation can be done at the panel level, at a group level (e.g. clusters, users vs. non-users, gender, etc.), or even at the individual level. Unless stated otherwise, the computations will be done for cluster 1, but could easily be adapted to other groups if needed.</p>
<div id="correlation" class="section level4 hasAnchor" number="10.4.3.1">
<h4><span class="header-section-number">10.4.3.1</span> Correlation<a href="data-analysis.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s start by evaluating the simplest relationship between the sensory attributes and overall liking by looking at correlations. Here, we are combining the average liking score per cluster to the sensory profile of the products. The correlations are then computed using the <code>cor()</code> function:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="data-analysis.html#cb397-1" aria-hidden="true" tabindex="-1"></a>data_cor <span class="ot">&lt;-</span> mean_cluster <span class="sc">%&gt;%</span></span>
<span id="cb397-2"><a href="data-analysis.html#cb397-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>N) <span class="sc">%&gt;%</span></span>
<span id="cb397-3"><a href="data-analysis.html#cb397-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Cluster, <span class="at">values_from =</span> Liking) <span class="sc">%&gt;%</span></span>
<span id="cb397-4"><a href="data-analysis.html#cb397-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(senso_mean <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Protein, Fiber)), <span class="at">by =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb397-5"><a href="data-analysis.html#cb397-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb397-6"><a href="data-analysis.html#cb397-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb397-7"><a href="data-analysis.html#cb397-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb397-8"><a href="data-analysis.html#cb397-8" aria-hidden="true" tabindex="-1"></a>res_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(data_cor)</span></code></pre></div>
<p>Various packages can be used to visualize these correlations. We opt here for <code>ggcorrplot()</code> from the <code>{ggcorrplot}</code> package as it provides many interesting visualization in <code>{ggplot2}</code>. This package also provides the function <code>cor_pmat()</code> which compute the p-value associated to each correlation. This matrix of p-value can be used to hide correlations that are not significant at the level defined by the parameter <code>sig.level</code>.</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="data-analysis.html#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot)</span>
<span id="cb398-2"><a href="data-analysis.html#cb398-2" aria-hidden="true" tabindex="-1"></a>res_cor_pmat <span class="ot">&lt;-</span> <span class="fu">cor_pmat</span>(data_cor)</span>
<span id="cb398-3"><a href="data-analysis.html#cb398-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(res_cor, <span class="at">type =</span> <span class="st">&quot;full&quot;</span>, <span class="at">p.mat =</span> res_cor_pmat, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">insig =</span> <span class="st">&quot;blank&quot;</span>, <span class="at">lab =</span> <span class="cn">TRUE</span>, <span class="at">lab_size =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-278-1.png" width="672" /></p>
<p>The average liking scores for cluster 1 (defined as <code>1 (74)</code>) are positively correlated with <code>Overall odor intensity</code>, <code>Fatty odor</code>, <code>Cereal flavor</code>, <code>Fatty flavor</code>, <code>Dairy flavor</code>, <code>Overall flavor persistence</code>, <code>Salty</code>, <code>Sweet</code>, <code>Warming</code>, <code>Fatty in mouth</code>, and <code>Melting</code>. They are also negatively correlated to <code>External color intensity</code>, <code>Astringent</code>, and <code>Dry in mouth</code>.
Finally, it can be noted that the correlation between clusters is high with a value of 0.72.</p>
</div>
<div id="linear-and-quadratic-regression" class="section level4 hasAnchor" number="10.4.3.2">
<h4><span class="header-section-number">10.4.3.2</span> Linear and Quadratic Regression<a href="data-analysis.html#linear-and-quadratic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Although the correlation provides a first good idea of which attributes are linked to liking, it only measures linear relationships and it does not allow for inference. To overcome this particular limitations, linear and quadratic regressions are used.</p>
<p>Let’s start by combining the sensory data to the average liking score per product for cluster 1. To simplify the analysis, all the sensory attributes are structured in the longer format.</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="data-analysis.html#cb399-1" aria-hidden="true" tabindex="-1"></a>data_reg <span class="ot">&lt;-</span> mean_cluster <span class="sc">%&gt;%</span></span>
<span id="cb399-2"><a href="data-analysis.html#cb399-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Cluster <span class="sc">==</span> <span class="st">&quot;1 (74)&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb399-3"><a href="data-analysis.html#cb399-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>N) <span class="sc">%&gt;%</span></span>
<span id="cb399-4"><a href="data-analysis.html#cb399-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(senso_mean <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(Protein, Fiber)), <span class="at">by =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb399-5"><a href="data-analysis.html#cb399-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(Shiny<span class="sc">:</span>Melting, <span class="at">names_to =</span> <span class="st">&quot;Attribute&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Score&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb399-6"><a href="data-analysis.html#cb399-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Attribute =</span> <span class="fu">factor</span>(Attribute, <span class="at">levels =</span> <span class="fu">colnames</span>(senso_mean)[<span class="dv">4</span><span class="sc">:</span><span class="fu">ncol</span>(senso_mean)]))</span></code></pre></div>
<p>Both the linear regression and the quadratic regression are then run on <code>Liking</code> per attribute:</p>
<blockquote>
<p>To add a quadratic model, two options are possible:
1. In <code>data_reg</code>, we could add a column (using <code>mutate()</code>) called <code>Score2</code> that is defined as <code>Score2 = Score^2</code>. The model for the quadratic regression is then defined as <code>Liking ~ Score + Score2</code>;
2. The quadratic model is informed directly using the <code>poly()</code> function by informing which polynomial degrees to consider (here <code>2</code>).
For its concision, we opt for the second option.</p>
</blockquote>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="data-analysis.html#cb400-1" aria-hidden="true" tabindex="-1"></a>res_reg <span class="ot">&lt;-</span> data_reg <span class="sc">%&gt;%</span></span>
<span id="cb400-2"><a href="data-analysis.html#cb400-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest_by</span>(Attribute) <span class="sc">%&gt;%</span></span>
<span id="cb400-3"><a href="data-analysis.html#cb400-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb400-4"><a href="data-analysis.html#cb400-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lin_mod =</span> <span class="fu">list</span>(<span class="fu">lm</span>(Liking <span class="sc">~</span> Score, <span class="at">data =</span> data)),</span>
<span id="cb400-5"><a href="data-analysis.html#cb400-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">quad_mod =</span> <span class="fu">list</span>(<span class="fu">lm</span>(Liking <span class="sc">~</span> <span class="fu">poly</span>(Score, <span class="dv">2</span>), <span class="at">data =</span> data))</span>
<span id="cb400-6"><a href="data-analysis.html#cb400-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>We extract the attributes that are significantly linked to liking (at 5%, and we accept 6% for quadratic effects). To do so, the results stored in <code>lin_mod</code> and <code>quad_mod</code> need unfolding (<code>summarize()</code>) and restructuring (<code>broom::tidy()</code>).</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="data-analysis.html#cb401-1" aria-hidden="true" tabindex="-1"></a>lin <span class="ot">&lt;-</span> res_reg <span class="sc">%&gt;%</span></span>
<span id="cb401-2"><a href="data-analysis.html#cb401-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(broom<span class="sc">::</span><span class="fu">tidy</span>(lin_mod)) <span class="sc">%&gt;%</span></span>
<span id="cb401-3"><a href="data-analysis.html#cb401-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb401-4"><a href="data-analysis.html#cb401-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;Score&quot;</span>, p.value <span class="sc">&lt;=</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span></span>
<span id="cb401-5"><a href="data-analysis.html#cb401-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Attribute) <span class="sc">%&gt;%</span></span>
<span id="cb401-6"><a href="data-analysis.html#cb401-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.character</span>()</span>
<span id="cb401-7"><a href="data-analysis.html#cb401-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb401-8"><a href="data-analysis.html#cb401-8" aria-hidden="true" tabindex="-1"></a>quad <span class="ot">&lt;-</span> res_reg <span class="sc">%&gt;%</span></span>
<span id="cb401-9"><a href="data-analysis.html#cb401-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(broom<span class="sc">::</span><span class="fu">tidy</span>(quad_mod)) <span class="sc">%&gt;%</span></span>
<span id="cb401-10"><a href="data-analysis.html#cb401-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb401-11"><a href="data-analysis.html#cb401-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">&quot;poly(Score, 2)2&quot;</span>, p.value <span class="sc">&lt;=</span> <span class="fl">0.06</span>) <span class="sc">%&gt;%</span></span>
<span id="cb401-12"><a href="data-analysis.html#cb401-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Attribute) <span class="sc">%&gt;%</span></span>
<span id="cb401-13"><a href="data-analysis.html#cb401-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.character</span>()</span></code></pre></div>
<p>These attributes are then represented graphically against the liking Scores.</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="data-analysis.html#cb402-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb402-2"><a href="data-analysis.html#cb402-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb402-3"><a href="data-analysis.html#cb402-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> data_reg <span class="sc">%&gt;%</span></span>
<span id="cb402-4"><a href="data-analysis.html#cb402-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Attribute <span class="sc">%in%</span> <span class="fu">unique</span>(<span class="fu">c</span>(lin, quad)))</span>
<span id="cb402-5"><a href="data-analysis.html#cb402-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb402-6"><a href="data-analysis.html#cb402-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Score, <span class="at">y =</span> Liking, <span class="at">label =</span> Product)) <span class="sc">+</span></span>
<span id="cb402-7"><a href="data-analysis.html#cb402-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb402-8"><a href="data-analysis.html#cb402-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>() <span class="sc">+</span></span>
<span id="cb402-9"><a href="data-analysis.html#cb402-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb402-10"><a href="data-analysis.html#cb402-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Attribute, <span class="at">scales =</span> <span class="st">&quot;free_x&quot;</span>)</span></code></pre></div>
<p>Let’s now add a regression line to the model. To do so, <code>geom_smooth()</code> is being used with as <code>method = lm</code> combined to <code>formula = 'y ~ x'</code> for linear relationships, and <code>formula = 'y ~ x + I(x^2)'</code> for quadratic relationships (when both the linear and quadratic models are significant, the quadratic model is used).</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="data-analysis.html#cb403-1" aria-hidden="true" tabindex="-1"></a>lm.mod <span class="ot">&lt;-</span> <span class="cf">function</span>(df, quad) {</span>
<span id="cb403-2"><a href="data-analysis.html#cb403-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(df<span class="sc">$</span>Attribute <span class="sc">%in%</span> quad, <span class="st">&quot;y~x+I(x^2)&quot;</span>, <span class="st">&quot;y~x&quot;</span>)</span>
<span id="cb403-3"><a href="data-analysis.html#cb403-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>We apply this function to our data by applying to each attribute (here we set <code>se=FALSE</code> to remove the confidence intervals around the regression line):</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="data-analysis.html#cb404-1" aria-hidden="true" tabindex="-1"></a>p_smooth <span class="ot">&lt;-</span> <span class="fu">by</span>(</span>
<span id="cb404-2"><a href="data-analysis.html#cb404-2" aria-hidden="true" tabindex="-1"></a>  df, df<span class="sc">$</span>Attribute,</span>
<span id="cb404-3"><a href="data-analysis.html#cb404-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) <span class="fu">geom_smooth</span>(<span class="at">data =</span> x, <span class="at">method =</span> lm, <span class="at">formula =</span> <span class="fu">lm.mod</span>(x, <span class="at">quad =</span> quad), <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb404-4"><a href="data-analysis.html#cb404-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb404-5"><a href="data-analysis.html#cb404-5" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> p_smooth</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-284-1.png" width="672" /></p>
<p>All attributes except <code>Astringent</code> are linearly linked to liking. For <code>Astringent</code>, the curvature is U-shaped: this does not show an effect of saturation as it would have been represented as an inverted U-shape. Although the quadratic effect shows a better fit than the linear effect, having a linear effect would have been a good predictor as well in this situation.</p>
</div>
</div>
<div id="prefmap" class="section level3 hasAnchor" number="10.4.4">
<h3><span class="header-section-number">10.4.4</span> External Preference Mapping<a href="data-analysis.html#prefmap" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ultimately, one of the goals of combining sensory and consumer data is to find within the sensory space the area that are liked/accepted by consumers. Since this approach is based on modeling and prediction, it may suggest area of the space with high acceptance potential which are not filled in by products yet. This would open doors to new product development.</p>
<p>To perform such analysis, the External Preference Mapping (PrefMap) could be used amongst other techniques. For more information on the principles of PrefMap, please refer to (ANALYZING SENSORY DATA WITH R or OTHER REFERENCES…).</p>
<p>To run the PrefMap analysis, the <code>carto()</code> function from <code>{SensoMineR}</code> is being used. This function takes as parameter the sensory space to consider (stored in <code>senso_pca$ind$coord</code>, here we will consider dimension 1 and dimension 2), the table of liking scores (as stored in <code>consumer_wider</code>), and the model to consider (here we consider the quadratic model, so we use <code>regmod=1</code>). For convenience, we run the analysis on the full panel since <code>consumer_wider</code> is (almost) already structured as needed.</p>
<p>Since <code>carto()</code> requires matrix or data frame with row names for the analysis, the data needs to be slightly adapted (we also need to ensure that the products are in the same order in both files).</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="data-analysis.html#cb405-1" aria-hidden="true" tabindex="-1"></a>senso <span class="ot">&lt;-</span> senso_pca<span class="sc">$</span>ind<span class="sc">$</span>coord[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="sc">%&gt;%</span></span>
<span id="cb405-2"><a href="data-analysis.html#cb405-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Product&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb405-3"><a href="data-analysis.html#cb405-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Product) <span class="sc">%&gt;%</span></span>
<span id="cb405-4"><a href="data-analysis.html#cb405-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb405-5"><a href="data-analysis.html#cb405-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb405-6"><a href="data-analysis.html#cb405-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb405-7"><a href="data-analysis.html#cb405-7" aria-hidden="true" tabindex="-1"></a>consu <span class="ot">&lt;-</span> consumer_wide <span class="sc">%&gt;%</span></span>
<span id="cb405-8"><a href="data-analysis.html#cb405-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Product) <span class="sc">%&gt;%</span></span>
<span id="cb405-9"><a href="data-analysis.html#cb405-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb405-10"><a href="data-analysis.html#cb405-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb405-11"><a href="data-analysis.html#cb405-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb405-12"><a href="data-analysis.html#cb405-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(SensoMineR)</span>
<span id="cb405-13"><a href="data-analysis.html#cb405-13" aria-hidden="true" tabindex="-1"></a>PrefMap <span class="ot">&lt;-</span> <span class="fu">carto</span>(<span class="at">Mat =</span> senso, <span class="at">MatH =</span> consu, <span class="at">regmod =</span> <span class="dv">1</span>, <span class="at">graph.tree =</span> <span class="cn">FALSE</span>, <span class="at">graph.corr =</span> <span class="cn">FALSE</span>, <span class="at">graph.carto =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-285-1.png" width="672" /></p>
<p>From this map, we can see that the optimal area (dark red) is located on the positive side of dimension 1, between <code>P01</code>, <code>P05</code>, and <code>P10</code> (as expected by the liking score).</p>
<p>Let’s now re-build this plot using <code>{ggplot2}</code>.</p>
<p>The sensory space is stored in <code>senso</code>, whereas the surface response plot information is split between:</p>
<ul>
<li><code>PrefMap$f1</code>: contains the coordinates on dimension 1 in which predictions have be made;</li>
<li><code>PrefMap$f2</code>: contains the coordinates on dimension 2 in which predictions have be made;</li>
<li><code>PrefMap$depasse</code>: contains the percentage of consumers that accept a product at each point of the space. This matrix is defined in such a way that <code>PrefMap$f1</code> links to the rows of the matrix, and <code>PrefMap$f2</code> links to the columns.</li>
</ul>
<p>Last but not least, <code>POpt</code> (which coordinates are stored in <code>senso_pca$ind.sup$coord</code>) can be projected on that space in order to see how this optimized sample is considered in terms of consumers’ liking/preference.</p>
<p>Let’s start with preparing the data by transforming everything back into a tibble:</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="data-analysis.html#cb406-1" aria-hidden="true" tabindex="-1"></a>senso <span class="ot">&lt;-</span> senso <span class="sc">%&gt;%</span></span>
<span id="cb406-2"><a href="data-analysis.html#cb406-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb406-3"><a href="data-analysis.html#cb406-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb406-4"><a href="data-analysis.html#cb406-4" aria-hidden="true" tabindex="-1"></a>senso_sup <span class="ot">&lt;-</span> senso_pca<span class="sc">$</span>ind.sup<span class="sc">$</span>coord <span class="sc">%&gt;%</span></span>
<span id="cb406-5"><a href="data-analysis.html#cb406-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Product&quot;</span>)</span>
<span id="cb406-6"><a href="data-analysis.html#cb406-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb406-7"><a href="data-analysis.html#cb406-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(PrefMap<span class="sc">$</span>nb.depasse) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">round</span>(PrefMap<span class="sc">$</span>f1, <span class="dv">2</span>), <span class="fu">round</span>(PrefMap<span class="sc">$</span>f2, <span class="dv">2</span>))</span>
<span id="cb406-8"><a href="data-analysis.html#cb406-8" aria-hidden="true" tabindex="-1"></a>PrefMap_plot <span class="ot">&lt;-</span> PrefMap<span class="sc">$</span>nb.depasse <span class="sc">%&gt;%</span></span>
<span id="cb406-9"><a href="data-analysis.html#cb406-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>(<span class="at">rownames =</span> <span class="st">&quot;Dim1&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb406-10"><a href="data-analysis.html#cb406-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>Dim1, <span class="at">names_to =</span> <span class="st">&quot;Dim2&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Acceptance (%)&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb406-11"><a href="data-analysis.html#cb406-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), as.numeric))</span></code></pre></div>
<p>To build the plot, different layers involving different source of data (<code>senso</code>, <code>senso_sup</code>, and <code>PrefMap_plot</code> that is) are required. Hence, the initiation of the plot through <code>ggplot()</code> does not specify any data. Instead, the data used in each step are included within the <code>geom_*()</code> of interest. In this example, <code>geom_tile()</code> (coloring) and <code>geom_contour()</code> (contour lines) are used to build the surface plot.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="data-analysis.html#cb407-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb407-2"><a href="data-analysis.html#cb407-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">data =</span> PrefMap_plot, <span class="fu">aes</span>(<span class="at">x =</span> Dim1, <span class="at">y =</span> Dim2, <span class="at">fill =</span> <span class="st">`</span><span class="at">Acceptance (%)</span><span class="st">`</span>, <span class="at">color =</span> <span class="st">`</span><span class="at">Acceptance (%)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb407-3"><a href="data-analysis.html#cb407-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour</span>(<span class="at">data =</span> PrefMap_plot, <span class="fu">aes</span>(<span class="at">x =</span> Dim1, <span class="at">y =</span> Dim2, <span class="at">z =</span> <span class="st">`</span><span class="at">Acceptance (%)</span><span class="st">`</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb407-4"><a href="data-analysis.html#cb407-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb407-5"><a href="data-analysis.html#cb407-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb407-6"><a href="data-analysis.html#cb407-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> senso, <span class="fu">aes</span>(<span class="at">x =</span> Dim<span class="fl">.1</span>, <span class="at">y =</span> Dim<span class="fl">.2</span>), <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb407-7"><a href="data-analysis.html#cb407-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> senso, <span class="fu">aes</span>(<span class="at">x =</span> Dim<span class="fl">.1</span>, <span class="at">y =</span> Dim<span class="fl">.2</span>, <span class="at">label =</span> Product)) <span class="sc">+</span></span>
<span id="cb407-8"><a href="data-analysis.html#cb407-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> senso_sup, <span class="fu">aes</span>(<span class="at">x =</span> Dim<span class="fl">.1</span>, <span class="at">y =</span> Dim<span class="fl">.2</span>), <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">cex =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb407-9"><a href="data-analysis.html#cb407-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> senso_sup, <span class="fu">aes</span>(<span class="at">x =</span> Dim<span class="fl">.1</span>, <span class="at">y =</span> Dim<span class="fl">.2</span>, <span class="at">label =</span> Product), <span class="at">col =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb407-10"><a href="data-analysis.html#cb407-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">mid =</span> <span class="st">&quot;white&quot;</span>, <span class="at">high =</span> <span class="st">&quot;red&quot;</span>, <span class="at">midpoint =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb407-11"><a href="data-analysis.html#cb407-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient2</span>(<span class="at">low =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">mid =</span> <span class="st">&quot;white&quot;</span>, <span class="at">high =</span> <span class="st">&quot;red&quot;</span>, <span class="at">midpoint =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb407-12"><a href="data-analysis.html#cb407-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">str_c</span>(<span class="st">&quot;Dimension 1(&quot;</span>, <span class="fu">round</span>(senso_pca<span class="sc">$</span>eig[<span class="dv">1</span>, <span class="dv">2</span>], <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb407-13"><a href="data-analysis.html#cb407-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">str_c</span>(<span class="st">&quot;Dimension 2(&quot;</span>, <span class="fu">round</span>(senso_pca<span class="sc">$</span>eig[<span class="dv">2</span>, <span class="dv">2</span>], <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb407-14"><a href="data-analysis.html#cb407-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;External Preference Mapping applied to the biscuits data&quot;</span>, <span class="st">&quot;(The PrefMap is based on the quadratic model)&quot;</span>) <span class="sc">+</span></span>
<span id="cb407-15"><a href="data-analysis.html#cb407-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-287-1.png" width="672" /></p>
<p>As can be seen, <code>POpt</code> is quite far from the optimal area suggested by the PrefMap. This suggests that prototypes with higher success chances could be developed.</p>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-stunkard1985" class="csl-entry">
Stunkard, Albert J, and Samuel Messick. 1985. <span>“The Three-Factor Eating Questionnaire to Measure Dietary Restraint, Disinhibition and Hunger.”</span> <em>Journal of Psychosomatic Research</em> 29 (1): 71–83.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="44">
<li id="fn44"><p>The <code>map()</code> function applies the same function to each element of a list automatically: It is hence equivalent to a <code>for ()</code> loop, but in a neater and more efficient way.<a href="data-analysis.html#fnref44" class="footnote-back">↩︎</a></p></li>
<li id="fn45"><p>We use the package <code>{formattable}</code> to print the results in percentage using one decimal. As an alternative, we could have used <code>percent()</code> from the <code>{scales}</code> package.<a href="data-analysis.html#fnref45" class="footnote-back">↩︎</a></p></li>
<li id="fn46"><p>The function <code>ifelse()</code> takes three parameters: 1. the condition to test, 2. the value or code to run if the condition is met, and 3. the value or code to run if the condition is not met.<a href="data-analysis.html#fnref46" class="footnote-back">↩︎</a></p></li>
<li id="fn47"><p>We would like to remind the reader that the liking scores measured on the categorical scale was reverted since 1 defined “I like it a lot” and 9 “I dislike it a lot”. To simplify the readability, this scale is reverted so that 1 corresponds to a low liking score, and 9 to a high liking score (in practice, we will take as value 10 - score given).<a href="data-analysis.html#fnref47" class="footnote-back">↩︎</a></p></li>
<li id="fn48"><p><code>scale()</code> allows centering (<code>center=TRUE</code>) and standardizing (<code>scale=TRUE</code>) data automatically in columns, hence generating <em>z-scores</em>.<a href="data-analysis.html#fnref48" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-prep.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="value-delivery.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/10-data-analysis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
